### ISSUE TITLE
Preselection of select options and updating many-to-many relations

### ISSUE THREAD

**Issue by dmetchev** [zofe/rapyd-laravel#100]
Hi there,
Is there a way to preselect options of a select element?
I have the following many-to-many relation and I need it in a select. (maybe multiple select in the future)

```
$genericContent->add('roles.role_id','Role','select')->options(Role::lists('name', 'id'));
```

How can this be made to preselect the proper options?
How can I update the roles relation?

I need something like sync().

Thanks!

**Comment by larylinz** [comment]
+1; how todo preselection on select?
