### ISSUE TITLE
Edit mode check duplicated record error

### ISSUE THREAD

**Issue by ckwong** [zofe/rapyd-laravel#109]
I set $edit->add('no','No', 'text')->rule('unique:servicerecords|no'); in edit form, to sure field no is unique, but it show "Method [validateNo] does not exist."

How to fix ?

**Comment by tacone** [comment]
Seems like the rule syntax is wrong. Try to check laravel's documentation.

**Comment by ckwong** [comment]
if should be rule('unique:servicerecords,no');
