### ISSUE TITLE
Handling Tables with Foreign Key to itself

### ISSUE THREAD

**Issue by siavash13** [zofe/rapyd-laravel#111]
We are developing a package which benefits from your package, I am a bit stuck it seems we can't handle the cases in which, a table has a field which a reference to another field of itself, for example 
Model1 {
   id : integer,
   name : Text,
   parent : integer
}
and parent refers to id of the same table, 
How do we have to initial the DataGrid and DataEdit to have a dropdown list of all rows of table as parent?

let's say we have Model1 how do we have to define its method such for example parent() to get this working 

 $grid = DataGrid::source(Model1::with('parent'));

**Comment by zofe** [comment]
In the demo  there is a model with a parent/child relation (http://www.rapyd.com/rapyd-demo/models category model),  the way to traverse  to get parent or childrens  is  an "eloquent stuff", you should define  it on your model.

I'not sure about what you need,  If you're thinking about a dropdown with a "tree" structure (useful to manage a  "parent/child" relation in a dataform)  there isn't a ready to use Field,  but  we can work on it.  It was present in a old version of  rapyd, so I can try to reimplement

**Comment by tacone** [comment]
Hello, if you're interested in nested tree traversals, you may take a look to Baum https://github.com/etrepat/baum

**Comment by siavash13** [comment]
tacoe and zofe Thanks for your helps, I have found them useful but I was making a mistake, therefore I was thinking maybe when a table has foreign key to itself the package doesn't handle it anymore, just realized the mistake was from me.
anyway thanks for your helps again
