### ISSUE TITLE
Update and insert Table without Updated_At Column

### ISSUE THREAD

**Issue by siavash13** [zofe/rapyd-laravel#113]
if we need to use Zofe/Rapyd for a ready database, we can't build it from scratch, so the timestamps fields (created_at, updated_at) don't exist. how can we perform the operations so that it works properly because I get the following error:
`SQLSTATE[42703]: Undefined column: 7 ERROR: column "updated_at" of relation`

**Comment by tacone** [comment]
Disable timestamps in your models http://laravel.com/docs/4.2/eloquent#timestamps

**Comment by siavash13** [comment]
Yes I just found it few minutes after posting it so I closed the issue

**Comment by fbarrerageo** [comment]
public $timestamps = false;
