### ISSUE TITLE
Localization fir DataFilter not working

### ISSUE THREAD

**Issue by serverfire** [zofe/rapyd-laravel#115]
I am using `Zofe/rapyd-laravel` I faced an issue I need to know if it's a bug or I am making mistake somewhere, when I changed the default language of the application most of the translations are properly working, except the search and the reset button in the `DataFilter`, the values remain `reset` and `search`

**Comment by zofe** [comment]
as you can see in the demo/wiki:
https://github.com/zofe/rapyd-laravel/wiki/DataFilter
you should specify names for each button..

if you look at the code:
https://github.com/zofe/rapyd-laravel/blob/master/src/Zofe/Rapyd/DataForm/DataForm.php#L175
https://github.com/zofe/rapyd-laravel/blob/master/src/Zofe/Rapyd/DataForm/DataForm.php#L190

you should also see that submit name  is required,  and reset name  is  optional (if not passed  it will try to find  a valid translation)

so.. if you use as in the demo:
    
       $filter->submit('search');
       $filter->reset('reset');

you're telling  to use  'search'  and 'reset'  as  button-labels.
