### ISSUE TITLE
can't get 'tags' to work

### ISSUE THREAD

**Issue by LPTT** [zofe/rapyd-laravel#119]
Hi,
I really like rapyd but I can't get tags to work.
My Models

```
class Praline extends Eloquent {
    protected $table = 'pralines';
    
    public function ingredients(){

        return $this->belongsToMany('Ingredient', 'pralines_ingredients', 'praline_id', 'ingredient_id');
    }
}
```
```
class Ingredient extends Eloquent {
    protected $tables = 'ingredients';

    public function pralines()
    {
        return $this->belongsToMany('Praline', 'pralines_ingredients', 'praline_id', 'ingredient_id');
    }
    
}
```

When I call 
```
$edit = DataEdit::source(new Praline());
        $edit->add('ingredients.name','Zutaten','tags');
```
in my Controller I only get an empty textfield.
Any ideas?

**Comment by zofe** [comment]
seems a model/eloquent problem,  maybe the  sequence of last 2 parameter  in the belongsToMany.

if you look at the demo models you have..

       public function categories() {
        return $this->belongsToMany('Zofe\Rapyd\Models\Category', 'demo_article_category', 'article_id','category_id');
       }
    ....
    public function articles()  {
        return $this->belongsToMany('Zofe\Rapyd\Models\Article', 'demo_article_category', 'category_id','article_id');
     }

as you can see  last 2 fields  are inverted in the two models

**Comment by tacone** [comment]
Also check if Rapyd's JS is properly included.

**Comment by LPTT** [comment]
got it. I must have overwritten {{ Rapyd::head() }} 
Thanks for the fast help.
