### ISSUE TITLE
using Soft Deleting / DataEdit withTrashed()

### ISSUE THREAD

**Issue by larylinz** [zofe/rapyd-laravel#120]
Does Rapyd support: $edit = DataEdit::source(Person::withTrashed()); ?

It throws: Class name must be a valid object or a string 

Thank you for all your effort creating and maintaining RAPYD!

**Comment by zofe** [comment]
I think  that  Person::withTrashed()  is like a Person::all() :
It return an eloquent "collection" which is not a valid source for the datagrid,  

DataGrid source  method expects an entity or  a Query builder  instance.

so something like that:

     DataGrid(Person::where('deleted', 1)->orWhere('deleted',0))
  
you can define a query scope in your entity to be more concise
