### ISSUE TITLE
Adding custom columns to grid

### ISSUE THREAD

**Issue by begmst** [zofe/rapyd-laravel#121]
How can I simply add custom columns to the grid? I want to add a link with id reference (like http://example.com/list?reference_id=$id), but it always makes url in encoded format and no parameters from row are set. Also I cannot set link text - it just shows {{link_text}} instead of proper title. I tried $grid->add() function, but it does not work for me.

**Comment by zofe** [comment]
using closure

        $grid->add('custom','Custom')->cell(function ($cell) {
            return 'custom.. code or view';
        });

      or using blade  syntax / php code
 
      $grid->add('{{ strtoupper($fieldname) }}','Custom');

**Comment by tacone** [comment]
@begmst, if you look carefully to the example provided by zofe, you'll notice you miss the '$'. As a rule of thumb, when there is syntax error in your blade string, rapyd just returns the template string, not the actual result.
