### ISSUE TITLE
How to manage 3 level fields dependency 

### ISSUE THREAD

**Issue by mepawan** [zofe/rapyd-laravel#122]
Hi,
how can be implemented 3 level dependency ? like User, country, states, city.  so in add user form states list should be according to the country and city list should be according to the state. 

Thanks,

**Comment by zofe** [comment]
unfortunately it's not possible  at this time:
https://github.com/zofe/rapyd-laravel/blob/master/src/Zofe/Rapyd/DataForm/Field/Field.php#L100
So the dot notation "field.related"  is supported only at 2 levels and not at 3 .

The reason for this simplification is in this method:
https://github.com/zofe/rapyd-laravel/blob/master/src/Zofe/Rapyd/DataForm/Field/Field.php#L477
with the "not so complex" business logic of update/insert for related fields.

if you think to extend or improve this class you're welcome, but it's not trivial to find a way to keep all current fields-types  (like checkboxgroup, tags, autocomplete)   compatible with both 2 and 3 level dependency

**Comment by tacone** [comment]
Saving more than 2 levels with Eloquent is arduous at the very least. That is: if you need to manage a complex database, Eloquent is not the right tool.

**Comment by zofe** [comment]
too many changes needed,  in future  we should try to handle a "child-form"  concept 
as other symfony inspired packages http://kristijanhusak.github.io/laravel-form-builder/
