### ISSUE TITLE
migrate to Laravel 5

### ISSUE THREAD

**Issue by siavash13** [zofe/rapyd-laravel#123]
Hi we have developed a package that benefits from this package, as you already have known, the Laravel 5 is released, do you have any plan to release the new version compatible with the Laravel 5?

**Comment by zofe** [comment]
Hi slavash, first of all I am proud that rapyd is used on some admin package including serverfire/panel. 
I'll try to move to laravel 5, but to be honest the work will be hard and will start from a complete rebuild.

No planned milestones,  but now that laravel 5 is out I can try to do something.

**Comment by tiger2wander** [comment]
:+1:

**Comment by zofe** [comment]
thanks to a PR of @tiger2wander there is a new branch https://github.com/zofe/rapyd-laravel/tree/2.0 where a initial release for L5 is in test.  It's not a rebuilt as I said  but a massive  fix of all old Facade dependencies and escaping on blade views.
there are some problems but seems a good point,  https://github.com/zofe/rapyd-laravel/pull/124

**Comment by zofe** [comment]
I'm removing the __2.0 branch__,  dev-master is  the right place for L5  version,  
asap  I'll start with  2.* tags  for L5

**Comment by zofe** [comment]
seems stable,  I've only an issue on intervention image / image field
