### ISSUE TITLE
Help about 'created_at' and 'updated_at' field

### ISSUE THREAD

**Issue by mepawan** [zofe/rapyd-laravel#127]
Hi,
Is there compulsory ot have 'created_at' and 'updated_at' field in crud item table?

because I have added 'Languages' in crud item and in languages table there is id, name, code. So it throws error that unknown columng 'updated_at'

Can you please guide me?

Thanks,

**Comment by zofe** [comment]
No, and the error you see is from Eloquent, not from Rapyd. 
You can use `public $timestamps = false;` in your entity
