### ISSUE TITLE
Intervention Image  class not recognized in L5

### ISSUE THREAD

**Issue by zofe** [zofe/rapyd-laravel#128]
I've a problem with Intervention Image bundled with Rapyd on Laravel 5.
  (in a crud with an image field /src/DataForm/Field/Image.php)  it throw a :
```
FatalErrorException in Image.php 
Class 'Intervention\Image\ImageManagerStatic' not found
```
The namespace seems correct, I really don't know how to fix this,
I've not included the laravel service provider, just used namespace..  I tried both  ImageManagerStatic  and ImageManager  but no success..

**Comment by tacone** [comment]
Quite clearly an autoloader issue. Delete the optimized bootloader (don't know if or where laravel 5 stores it), clean every cache you can with `artisan' and try to re-run `composer dump-autoload`. If it does not work, try to delete the Intevention Image from the `vendor` folder and re-install it with `composer update`.

If all else fails, manually check the generated autoloader inside `vendor/composer`

**Comment by zofe** [comment]
thanks, tried all (dump, forcing optimization, recreating vendor) but no way,  the generated psr-4 autoload seems good:

     'Intervention\\Image\\' => array($vendorDir . '/intervention/image/src/Intervention/Image'),

namespace and path are correct, really strange behavior.

**Comment by tacone** [comment]
I tried downloading rapyd and instantiating the class via `php -a` and it worked. I'll try with a Laravel 5 instllation on monday.

**Comment by zofe** [comment]
I'm sorry tac thanks a lot for your time,  using zofe/rapyd 2.0 as package in L5  Intervention/image works (one main vendor).
It doesn't work in my __"dev"__ environment where I have direct dependency in laravel composer, so 2 main vendors:

		"psr-4": {
			"App\\": "app/",
		        "Zofe\\Rapyd\\": "packages/zofe/rapyd/src/"
		}

So as you said now I'm convinced that is an autoload issue,  I just can't figure if there is the fault (mine)
