### ISSUE TITLE
DataSet/DataGrid with array on L5 

### ISSUE THREAD

**Issue by Elbandi** [zofe/rapyd-laravel#129]
I got this on L5:

    Fatal error: Class 'Illuminate\Support\Facades\Paginator' not found in /foo/bar/vendor/zofe/rapyd/src/DataSet.php on line 188

I use data array as source.

**Comment by zofe** [comment]
Laravel  Paginator was moved on a different package  and different namespace I'll fix, 
this afflict only DataSet built with "array" as source

**Comment by zofe** [comment]
can you try again?  (after a composer update)

**Comment by Elbandi** [comment]
call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Support\Collection' does not have a method 'getFrom' Line 445

**Comment by Elbandi** [comment]
And i think the parameters are not good. Paginator::make declaration:

    public function make(array $items, $total, $perPage = null)

L5 Paginator contructor:

    public function __construct($items, $perPage, $currentPage = null, array $options = [])

**Comment by zofe** [comment]
ok, I will try to fix asap

**Comment by zofe** [comment]
should be "fixed" https://github.com/zofe/rapyd-laravel/commit/7212d3a53ccfac83ea45f37e97d451d38176a1f9 however there are some big changes, so  things like custom "views" are not working anymore.

**Comment by zofe** [comment]
seems fixed,  no feedback so i close this.
