### ISSUE TITLE
datagrid, arrays, No action key

### ISSUE THREAD

**Issue by Elbandi** [zofe/rapyd-laravel#130]
If the source is an array, no action key:
https://github.com/zofe/rapyd-laravel/blob/master/src/DataGrid/DataGrid.php#L199

gettype($tablerow) == "array"

few lines earlier you check the tablerow type (is_oject, is_array), but here not.

**Comment by zofe** [comment]
You should post some code of your DG (in this case the "source" you used can help too).

First of all about DG & arrays support:
-  DG can work with "multidimensional array"  (where source is an "array of rows" and rows are "array of cells") but each row must be an associative array (fieldname=>fieldvalue)  I.E.:

        //multidimensional array
        $articles = array (
            array (
                'id' => 1,
                'title' => 'Article 1',
            ),
            array (
                'id' => 2,
                'title' => 'Article 2',
            ),
        );

- DG can work with "array of object" (where the source is a "array of rows" and rows are "objects") but each object must have a property for each DG column, I.E.:

        //array of object
        $row1 = new \stdClass();
        $row1->id = 1;
        $row1->title = 'Article 1';
        $row2 = new \stdClass();
        $row2->id = 2;
        $row2->title = 'Article 2';
        $articles = array($row1, $row2);
        
If you have one of this source   this code will work for both:

        $grid = DataGrid::source($articles);
        $grid->add('id','ID', true);
        $grid->add('title','Title', true);

**Comment by Elbandi** [comment]
try this:

        //multidimensional array
        $articles = array (
            array ( 'id' => 1, 'title' => 'Article 1', ),
            array ( 'id' => 2, 'title' => 'Article 2', ),
        );
        $grid = DataGrid::source($articles);
        $grid->edit('/foo', 'Title', 'show', 'id');

and look the generated href url!  id value is missing

    <a href="/foo?show="><span .....</a>
                       ^

**Comment by zofe** [comment]
as I said,  "Action columns are not made to work with array datasources", I can try to let it work.
just curious why you're using arrays as source for datagrid if you've an entity?

**Comment by Elbandi** [comment]
i'm learning laravel. my internal project for this gets the data from external source (an output from a process), so no database is exists.
i display the data with datasource, and want an action for a row. but the key is missing from the action url. that's a bug: because the keyvalue is get as if tablerow were an object. but tablerow is an array, so keyvaule will be null/anything. i linked the incorrect line.

**Comment by tacone** [comment]
Having buttons for arrays is pretty much pointless.

See if this works though:

```php
$grid = DataGrid::source($articles);
$grid->add('<a href="/foo?show={{ $id }}">Show</a>');
```

**Comment by Elbandi** [comment]
https://github.com/Elbandi/rapyd-laravel/commit/3fe45a4f0e7fe8a171144b7b5ba042d822b217e2

**Comment by snapple42** [comment]
I did this and it's a workaround:

```php
    $grid->add('edit','Action')->cell(function() { return "";});
	$grid->row(function($row) {
			$id = $row->cell('id');
			$row->cell('edit')->value = sprintf('<a href="/functions/edit/?show=%s" title="Show" class=""><span class="glyphicon glyphicon-eye-open"> </span></a>
    		<a href="/functions/edit/?modify=%s" title="Modify" class=""><span class="glyphicon glyphicon-edit"> </span></a>
    		<a href="/functions/edit/?delete=%s" title="Delete" class="text-danger"><span class="glyphicon glyphicon-trash"> </span></a>',$id,$id,$id);
		});
```

You just need to modify where the "a href" is going... Also assumes "ID" is the key for the table.

**Comment by zofe** [comment]
https://github.com/Elbandi/rapyd-laravel/commit/3fe45a4f0e7fe8a171144b7b5ba042d822b217e2 seems merged in the master
