### ISSUE TITLE
adding a link to a datagrid cell

### ISSUE THREAD

**Issue by HassanKanj** [zofe/rapyd-laravel#132]
Hi,

I am trying to add a link to one of the grid columns, I added a picture that includes the problem I am having, the closest one to what I want is the 3rd one, but I don't want the curly braces to be part of the final output

![grid](https://cloud.githubusercontent.com/assets/6857592/6312930/72099598-b998-11e4-8c4f-32ca0b87e8da.jpg)

any ideas?

**Comment by zofe** [comment]
probably you need: `$grid->add('<a href="/blabla/?id={{ $field }}">testing</a>','Testing');`
curly bracket in blade syntax  are around  a "var"  not around an html output.

**Comment by HassanKanj** [comment]
Thank you, it worked

**Comment by MehmetOzkose** [comment]
$grid->add('<a href="/blabla/?id={{ $field }}"> {{ $testing }}</a>','Testing');

works for laravel 5.1
