### ISSUE TITLE
Change link for edit and delete

### ISSUE THREAD

**Issue by SteveAzz** [zofe/rapyd-laravel#133]
Is there anyway where I can override the edit and delete link inside of the DataGrid when I do.
        `$grid->edit('/memories/uri', 'Edit','modify|delete');`
Or at least is there any way i can add raw html to the table?

Basically what I want to do is have the edit and delete button follow the laravel 5 routeing convention like 
items/1/edit as a link. I hope this is possible.

**Comment by zofe** [comment]
"edit()" method is made to work with a dateedit  so it  can only follow the dataedit url semantic (so querystring modify|delete  etc..).
You're free to make custom links i.e.: `$grid->add('<a href="/items/{{ $id }}/edit">edit</a>','Edit');`
to any route  if you're not using dataedit for crud.

About laravel 5 routing convention, rapyd widgets  will be powered by  https://github.com/zofe/burp so in future there will be a chance to change url semantic from a routing file.
