### ISSUE TITLE
Hashing the password in DataEdit

### ISSUE THREAD

**Issue by HassanKanj** [zofe/rapyd-laravel#135]
Hello,
I am using the DataEdit to perform CRUD operations, I have a password field in the form, I want to hash the password on add/modify before saving the form, how should I implement the hashing in DataEdit?

**Comment by HassanKanj** [comment]
Problem solved using model events http://laravel.com/docs/5.0/eloquent#model-events

**Comment by zofe** [comment]
or a "murator", 
http://laravel.com/docs/5.0/eloquent#accessors-and-mutators
