### ISSUE TITLE
DataForm readonly edit

### ISSUE THREAD

**Issue by mehrdd** [zofe/rapyd-laravel#137]
Hi,
I have this :
```php
$form->text('created_by', 'Writer')->mode('readonly');
```
The created_by field is a numeric field that is related to User model.
And of course the result of this code will be the user-id ..

My question: Is there any way to edit the result of the readonly field ?
I want to manipulate the result ...
Something like :
```php
$form->text('created_by', 'Writer')->mode('readonly')->edit(function($result)
{
    return 'Writer Name : ' . userid_to_username($result);
});
```
Thanks

**Comment by zofe** [comment]
https://github.com/zofe/rapyd-laravel/wiki/Default-values
