### ISSUE TITLE
Pager links don't have html entities escaped

### ISSUE THREAD

**Issue by tormit** [zofe/rapyd-laravel#138]
This corrupts links when some parameter matches with html entity like _&reg_. Escaped link would look like  _\&amp;reg_

**Comment by tormit** [comment]
After some digging, I found out that this issue belongs to Laravel after all.
Closing.

**Comment by zofe** [comment]
I'm moving from laravel pagination to a custom one,  because I need more isolation on all widget's urls/routes.
I'm not sure that this can help, but It will impact for sure. I'll open a new issue to explain this choice to all.
