### ISSUE TITLE
Redirect after successful form submit 

### ISSUE THREAD

**Issue by sateesh15july** [zofe/rapyd-laravel#139]
Hello,

I want to redirect to on another route/url after successful DataForm or DataEdit. Please help me to shortout this issue.

Thanks

**Comment by zofe** [comment]
about dataform, in the documentation is explained that you need to use "return $form->view"  to  handle redirect..:
 ```php
        ....
        $form->saved(function() use ($form)
        {
            $form->model->password = md5(Input::get('password'));
            $form->model->save();
            return \Redirect::to('/user/welcome');
                
        });
       $form->build();
       return $form->view(.....);
```

with dataedit you should have: `$edit->back('insert|update|do_delete', $url);`

**Comment by sateesh15july** [comment]
I have try it but it not working: return \Redirect::to('/user/welcome');

**Comment by zofe** [comment]
please post the complete action of your controller

**Comment by sateesh15july** [comment]
public function anyAddNew()
{
	$this->layout->title = 'New Ship Method';
	$form = DataForm::source(new ShipMethod);
	$form->add('carrier','Carrier', 'text')->rule('required');
	$form->add('code','Code', 'text')->rule('required');
	$form->add('description','Description', 'textarea')->attributes(array('rows'=>2))->rule('required|min:5');
	$form->submit('Save');
	
	$form->saved(function () use ($form) {
		return Redirect::to('shipMethod.ship_methods')->with('message' , 'Ship method create successfully');
    });
	
	$this->layout->content = View::make('shipMethod.add_new', compact('form'));
}

**Comment by sateesh15july** [comment]
and following is code for data edit:

public function anyEdit()
{
	$this->layout->title = 'Edit Ship Method';
	
	$edit = DataEdit::source(new ShipMethod);
	$edit->add('carrier','Carrier','text')->rule('required');
	$edit->add('code','Code','text')->rule('required');
	$edit->add('description','Description','textarea')->attributes(array('rows'=>2))->rule('required');

	$edit->saved(function () use ($edit) {
		return Redirect::to('shipMethod.ship_methods')->with('message' , 'Ship method updated successfully');
    });
	
	$this->layout->content = View::make('shipMethod.edit_ship_method', compact('edit'));
}

**Comment by zofe** [comment]
as shown before to proper manage redirect  you should use:

       $form->build();
       return $form->view(.....);

because $form->view()  method check it there are redirects to perform.
Anyway you can also check  $form->hasRedirect(), after build method,  to  make a "return"  instead a $this->layout->content

**Comment by sateesh15july** [comment]
Thanks for response but still I have confuse how to use redirect with message. Above are my both add new and edit form.

It would be great if you send me which exact code need to add.

I only want redirect if record successfully inserted/updated.

Thanks

**Comment by zofe** [comment]
it's just an "if"
```php
...
$edit->saved(function () use ($edit) {
        return Redirect::to('shipMethod.ship_methods')->with('message' , 'Ship method updated successfully');
});
$edit->build();

if ($edit->hasRedirect()) {
    return $edit;
} 
$this->layout->content = View::make('shipMethod.edit_ship_method', compact('edit'));
```

**Comment by maximusblade** [comment]
...perhaps I missed it.
this isnt in the documentation ?

**Comment by tacone** [comment]
Interesting, I did not know about that. Does it also work with the DataForm?

**Comment by zofe** [comment]
yes..
sorry for the doc:
https://github.com/zofe/rapyd-laravel/wiki/DataForm#redirect-on-success
