### ISSUE TITLE
problem with image link (on modify)

### ISSUE THREAD

**Issue by HassanKanj** [zofe/rapyd-laravel#140]
Hi,

I have tried the following in my DataEdit image field:

1-
```
->move('uploads/test.jpg");
```
in the above case the image is saved to MyAppDir/uploads/test.jpg
and the image link when I click [modify] is: http://localhost:8000/uploads/test.jpg

2-
```
->move('public/uploads/test.jpg");
```
in the above case the image is saved to MyAppDir/public/uploads/test.jpg (which is what I want)
and the image link when I click [modify] is: http://localhost:8000/public/uploads/test.jpg 

what I want is the following:
- when saving the image, I want it to be saved inside public/test.jpg
- when I click [modify] I want the link appearing near the image preview to be http://localhost:8000/uploads/test.jpg (<= without the 'public' dir appearing in the url)

I am using Laravel5 - Rapyd 2.0.5

**Comment by zofe** [comment]
the preview link can be fixed using webPath() method:
https://github.com/zofe/rapyd-laravel/blob/master/src/DataForm/Field/File.php#L171
https://github.com/zofe/rapyd-laravel/blob/master/src/DataForm/Field/File.php#L241

**Comment by HassanKanj** [comment]
Thank you so much, it worked
