### ISSUE TITLE
Generators

### ISSUE THREAD

**Issue by kamilersz** [zofe/rapyd-laravel#143]
I know that rapyd provide widgets, not "code generation". But, since sometimes webapps may handle DB with lots of tables and column, code generation might be needed to minimize the work (of course, I am lazy :tada: )

Can we make another project to accomodate "code generation for rapyd-laravel" ?

**Comment by zofe** [comment]
I'm lazy too :+1:  
A console command  with simple input argument "Entity"   can use something like:.´Schema::getColumnListing(Entity->getTable());´  
to obtain all columns and write a controller from a stub one with some widgets.

But, I'm not sure that is simple to recognize correct field types,  fill values for related etc.
Anyway yes feel free to:
- fork (if you think that this command is general purpose) so I can accept PR,  or
- make another package to be more independent

**Comment by zofe** [comment]
no news and no time to do this stuff, so I close it for now.
