### ISSUE TITLE
How to add custom message to a specific field when validation fails

### ISSUE THREAD

**Issue by mip-ro** [zofe/rapyd-laravel#145]
I am unable to add a custom message for when validation fails for a specific field in my DataForm. I ask because i have a multilanguage site and want to show a "trans('message')" for when the validation fails.

Thanks

**Comment by zofe** [comment]
first of all, validation and translation are "laravel" stuffs, so you must be sure to have  resources/lang/xx/validation.php    where xx is your current locale.
As you can read at the end of resources/lang/en/validation.php,  you can add custom messages there (for english, and in the other validation.php for other languages)

then..  you can also pass to the  dataform / dataedit a validator instance:
```php
$form = DataForm::source(Article::find(1));
$form->validator = Validator::make(Input::all(), $rules, $messages);
...
```
in this way you can manage rule % messages as you wish.

then.. you cal also trigger an error  if validation pass.. but you need to check someting server-side:
```php
...
 $form->passed(function () use ($form) {
            if (someting...) {
                 $form->error("..mm there is a problem !");
            } else {
                $form->error("ok saved!");
            }
            $form->link("/mycontroller/form","back to the form");
 });
```

**Comment by mip-ro** [comment]
Thanks for the fast answer. It works just as you described it.
