### ISSUE TITLE
How to set up routing?

### ISSUE THREAD

**Issue by haayman** [zofe/rapyd-laravel#146]
I'm trying to set up a simple CRUD site for several tables, but I'm having trouble setting up the routing. I keep getting 'Bad method call exception's when trying an update.
Also: in the online examples there are no hints how to set this up. Or at least I can't find them

Or should I use the routes.php in rapyd/src? It seems very complicated and doesn't really make the use of this plugin very simple

**Comment by zofe** [comment]
please be more detailed.
The demo: http://www.rapyd.com/rapyd-demo/grid
show you that using correct "uri" in `$grid->edit()` and  `$edit->link()` that you join "lists" and "editing" widgets running  a full crud using a single line in your router as explained here:
https://github.com/zofe/rapyd-laravel#in-short

rapyd widget are mainly driven by query string, application routing is "your responsibility".

**Comment by haayman** [comment]
The grid works just fine, it's the DataEdit form that doesn't work.

When I try to post the 'edit order' form  to /order/edit?update=1 I get a MethodNotAllowedHttpException.

In OrderController:
    public function edit( Order $order ) {
        $edit = DataEdit::source( new Order());
        $edit->add('title', 'Title', 'text');
        // [snip]
        return $edit->view('orders.edit', compact('edit')
    }
    public function update() {
        $order = findOrFail( Input::get('update'));
        $order->update( Input::all());
        return redirect( action('OrderController@index'));  
    }

in orders/edit.blade.php:
    @extends('app')
    @section('content')
    {!! $edit !!}
    @endsection

in routes.php
    Route::get('/order', 'OrderController@index');
    Route::get('/order/edit', 'OrderController@edit');
    Route::post('/order/edit', 'OrderController@update');

**Comment by zofe** [comment]
first of all you're mixing dataedit code with other code (canonical way to manage a crud with laravel). You can't.
The reason you see "Route::any"  in my code is bacause DataEdit need to manage many http methods  (get, post, patch, delete)  so "any"  just  catch it all. 
As explained here https://github.com/zofe/rapyd-laravel/wiki/DataEdit  DataEdit is a full crud for an entity, you need only one action (that works on any http method so:
```php
Route::any('/order/edit', 'OrderController@edit');
//is enough
```

**Comment by haayman** [comment]
Ah, I get it now (so far at least :-)), thanks!
