### ISSUE TITLE
DataEdit & save hasone file

### ISSUE THREAD

**Issue by ckwong** [zofe/rapyd-laravel#147]
refer to a case use belongsTo relations within DataEdit

$edit = DataEdit::source(new Article);
$edit->add('author.firstname','Author', 'text');

Article hasone relation to author, how to update author tables when update article table in 
same time ?
...

**Comment by zofe** [comment]
As you said, usually  article __belongsTo__ author,  this relation is not  article __hasOne__ author.

In the rapyd demo (model, dataform, etc) there are many king of relations, you can find  how to manage "hasOne" here: http://www.rapyd.com/rapyd-demo/edit?modify=1  "Note" field.
