### ISSUE TITLE
Datagrid Relationships not working in Laravel 5

### ISSUE THREAD

**Issue by sparkeleven** [zofe/rapyd-laravel#149]
Models: Zone belongsTo Currency

using any combination of the following will not render the relationship value:
        $grid->add('{{ $currency->name }}','Currency', true); //field name, label, sortable
        $grid->add('{{currency.name','Currency', true); //field name, label, sortable
        $grid->add('{!! $currency->name !!}','Currency', true); //field name, label, sortable

but simply outputs: {{ $currency->name }} except for '{!!...' which renders a blank. Before I spend more time diagnosing this - do you already have a fix?

**Comment by zofe** [comment]
https://github.com/zofe/rapyd-laravel/issues/75

in short:
- you should use eager loading to reduce query number
- if there are errors in your relations  or  unmached relations  (in this case  $currency->name is a code error)  the DG just print it as  string.
- you should  fix it with model accessors, or simply silent with {{ @$relation->fieldname }}

**Comment by sparkeleven** [comment]
Ok, I see the rationale in requiring eager loading. Using ::with() for the relationships works.
