### ISSUE TITLE
XSS Attack on URL parameters

### ISSUE THREAD

**Issue by azamuddin** [zofe/rapyd-laravel#153]
I use rapyd DataGrid on my article page. But when it is tested for QA, the team found xss vulnerability on URL parameters

I give you example parameters that resulting in script alert on the page.

      http://10.100.92.99:8007/admin/my-articles?ord=title<script>alert("XSS can be injected");</script>

the my-articles route uses Rapyd DataGrid. On Chrome the script won't run, but resulting in SQL Query error message displayed. Meanwhile, on Firefox the script will run alert and same SQL Query error message is displayed saying no column 'title'  while actually the column exist.

Please help.

**Comment by tacone** [comment]
@azamuddin most likely the parameters you cite got stripped by github own xss defences. Try to paste it again using a code block or use a pastebin.

**Comment by zofe** [comment]
Just to explain what I tagged as BUG:
I'll fix is only the "missed  check" on order by field on dataset/grid.

There is no "xss" I can check  ...and  you've all instruments to escape columns value (by default a filter is on,  but if you use blade/alternative syntax is your responsability to strip or escape cell values)

**Comment by azamuddin** [comment]
Yeah, you example the xss can't run. But in my site when I use firefox the script ran.

this is my URL : http://localhost:3000/itjen/site/public/admin/my-articles?ord=title<script>alert("XSS injected")</script>

and this is the result
![screen shot 2015-04-18 at 08 11 39](https://cloud.githubusercontent.com/assets/3477408/7213266/4fde99e2-e5a2-11e4-8916-349ac8c65198.png)

**Comment by tacone** [comment]
Ok, so we have two separate holes inside the datagrid: 
```
http://www.rapyd.com/rapyd-demo/grid?ord=title%3Cscript%3Ealert%28%22XSS%20injected%22%29%3C/script%3E
```

This does not happens inside the widget itself, but thanks to the error message:

```
        SQLSTATE[42S22]: Column not found: 1054 Unknown column 'title<script>alert("XSS injected")</script>' in 'order clause' (SQL: select * from `demo_articles` order by `title<script>alert("XSS injected")</script>` asc limit 10 offset 0) Line 620
```

The first consideration is that error messages should be escaped too, since they're supposed to show up in the HTML.

The second consideration is that perhaps it is a nice chance to apply the workaround suggested in #105. That way no error messages inside the HTML, the exception handler would do all the work (stacktrace in debug mode or courtesy page in production).

**Comment by tacone** [comment]
Seems like the fix just landed https://github.com/zofe/rapyd-laravel/commit/4b46d58e077e318ae88aa4c705294b7c3aa6c2cf Could you try it and let us know? :)

**Comment by zofe** [comment]
yes,  I removed custom error output  (used in DF and DG) to leave laravel to handle errors and  as  @tacone  suggested (thanks).
Then  I've introduced also a check  on DataGrid,  so order by is allowed only for orderby  columns.
On DataSet instead its possible to restrict  available ordeby fields using a method:
https://github.com/zofe/rapyd-laravel/wiki/DataSet

**Comment by azamuddin** [comment]
Ok, how do I try the fix? I have ran composer update Zofe/rapyd, but it's still the same.. *sorry for my dumb question.

**Comment by zofe** [comment]
You are on L4 ? 
As you can see from the commit https://github.com/zofe/rapyd-laravel/commit/4b46d58e077e318ae88aa4c705294b7c3aa6c2cf this changes are made on master and 2.* tags/versions  this mean that are for L5

**Comment by azamuddin** [comment]
Yes, I'm on laravel 4. Could you please provide fix for L4 too?

**Comment by zofe** [comment]
done, update again

**Comment by tacone** [comment]
For some weird reason, updating does not bring your last commit when using `"zofe/rapyd":"1.3.*"`, while using `"zofe/rapyd": "1.3.29"` works properly.
I'm saying this here because @azamudin may get the same issue, while updating.

Weird enough, on composer the 1.3.x-dev tag has an older commit compared to 1.3.29.
https://packagist.org/packages/zofe/rapyd

**Comment by zofe** [comment]
it's because I've checkout-ed a tag instead using dev branch,  It's perfectly fine.
I've a L4 project with "zofe/rapyd":"1.3.*", tested,  it downloads the last 1.3.29

**Comment by tacone** [comment]
So it won't work for those not using prefer-stable?

**Comment by zofe** [comment]
https://packagist.org/packages/zofe/rapyd  I've right.. dev should be updated now
I hate github, and you ;)

**Comment by tacone** [comment]
Let's close this, we'll reopen if @azamuddin has further issues.
I tested the exception page today, and it popups as it should, so there should be no XSS now.

**Comment by azamuddin** [comment]
Thank a lot guys, he XSS has gone. I've successfully updated the package. You rock! :D

**Comment by ShrwdFlrst** [comment]
Hi @zofe 
This still seems to be an issue if you send the payload inside a custom param e.g. open the following in Firefox (doesn't work in Chrome because of the XSS Auditor)
http://www.rapyd.com/rapyd-demo/grid?a=a%22%3E%3Cscript%3Ealert%28%27hello%27%29%3C%2fscript%3E%20%3Cspan
Can also replicate locally when using laravel 5 and rapyd 2.0.10

**Comment by zofe** [comment]
some suggestion to solve the issue?

**Comment by tacone** [comment]
Check the HTML source of that link and see where the script tags appear :)

**Comment by ShrwdFlrst** [comment]
Can we remove the urldecode inside the URL::unparse_str so the query string remains encoded after append/remove/etc are called? 
E.g. https://github.com/ShrwdFlrst/rapyd-laravel/commit/9a1c783585059e5f0cf7e816d96c380468d83787

**Comment by tacone** [comment]
No that's the wrong approach, it would lead to a mess. The right one is to find where the var is printed out and escape it there.

It is printed in the pagination and table headers. Try to take a look to the blade templates, and see if you can escape it there.

**Comment by tacone** [comment]
Right here for example: https://github.com/zofe/rapyd-laravel/blob/master/views/datagrid.blade.php

```html
                    <a href="{!! $dg->orderbyLink($column->orderby_field,'asc') !!}">
                        <span class="glyphicon glyphicon-arrow-up"></span>
                    </a>
                @endif
                @if ($dg->onOrderby($column->orderby_field, 'desc'))
                    <span class="glyphicon glyphicon-arrow-down"></span>
                @else
                    <a href="{!! $dg->orderbyLink($column->orderby_field,'desc') !!}">
                        <span class="glyphicon glyphicon-arrow-down"></span>
```

those exclamation points mean trouble.

As for the pagination I have no clue.

**Comment by ShrwdFlrst** [comment]
It looks like the pagination is generated inside DataSet::links, the Url object is appended to the Laravel Paginator, and urldecoded again before being printed unescaped. 
https://github.com/zofe/rapyd-laravel/blob/master/src/DataSet.php#L255

The pagination is printed out on the line below - but turning on escaping does so for both the urls and the surrounding Paginator html, which we don't want:
https://github.com/zofe/rapyd-laravel/blob/master/views/datagrid.blade.php#L46

So as you said can we escape the order by links. And for the pagination, don't urldecode, like this?:
https://github.com/ShrwdFlrst/rapyd-laravel/commit/5b0765875d27543ef8e0c16b486cc91e27c120f8

**Comment by tacone** [comment]
Yes, I think that stripping urldecode for the pagination would be fine and appropriate. Could you give both a go and eventually send a pull request? I guess Zofe would have no problem to merge it.

Thank you for your help :)

**Comment by ShrwdFlrst** [comment]
PR created, cheers @tacone :)

**Comment by zofe** [comment]
thanks @ShrwdFlrst and thanks @tacone, it is a pleasure working with you
