### ISSUE TITLE
Rapyd works only with primary key = 'id'

### ISSUE THREAD

**Issue by rpg999** [zofe/rapyd-laravel#161]
I often call the primary key of a table like `id_table_name` . So when i start using Rapyd , i get the error because Rapyd tries to get all entries from the table by the primary key `id`. 
Something like that `select * from `stage` order by `id` desc limit 10 offset 0)`.

Is that a bug ? How can i point to Rapyd the primary key that i want ?

Sorry for my bad English .
Thank you.

**Comment by zofe** [comment]
it's not a rapyd  question,  rapyd sniff PK  from your eloquent models.

**Comment by rpg999** [comment]
Thank for you fast answer. I'm pretty new in Laravel , so i didn't know about that .

**Comment by zofe** [comment]
ok, if this solve  your problem  please remember to close the issue.
