### ISSUE TITLE
Pagination total count

### ISSUE THREAD

**Issue by farynato** [zofe/rapyd-laravel#162]
First of all, congratulations for the package, it's amazing!
I have a little problem. I want to obtain in my datagrid's view the total count of pagination (total number of rows) and I don't find the solution. Could you help me?
Thank you in advance and sorry for my English.

**Comment by farynato** [comment]
I found the solution. Sorry!

**Comment by zofe** [comment]
hi, in this case is a good option to share your solution with others.
(closed issues  are searchable)

**Comment by farynato** [comment]
You are right. In fact I thought that it was rather easy looking DataSet methods, but I was wrong.
I found the solution using getSet(). In my case I did:

$set = $grid->paginate(20)->getSet(); 
$num_rows = $set->data->total(); 

In this way, I get the number of rows I was looking for, however, using this method I obtain 40 registers in each page because they are repeated. The DataGrid is build two times, first 20 registers and then the same 20 registers. Any solution for this?

Thank you very much.

**Comment by zofe** [comment]
sure,  DS (and so also DG)    have a public property "paginator"  so you can use:

    {{ $grid->paginator->total() }} 

and all this stuff:
http://laravel.com/api/5.0/Illuminate/Contracts/Pagination/LengthAwarePaginator.html#method_total

**Comment by farynato** [comment]
Thank you for your help, but that doesn´t work for me.
I obtain this error:

Call to a member function total() on a non-object

The object $grid->paginator is null....

**Comment by zofe** [comment]
you're on Laravel 4 ?

**Comment by farynato** [comment]
I'm on Laravel 5.
At the moment, I've found one solution:
I call to method getSet() when I'm creating the grid:

$grid = \DataGrid::source(Raton::with('padre'))->getSet();

After that, I can obtain the number of collections loaded in data property of grid like this:

$num_rows = $grid->data->toBase()->count();

**Comment by zofe** [comment]
you have a paginator only if (and after) you use  paginate:
$grid->paginate(10); 
$grid->paginator->total();

**Comment by farynato** [comment]
Yes, I supossed it. But in my case the object paginator is null, it isn`t loaded with any data. I think that method build in DataSet (that is the parent of build in DataGrid) only creates the paginator when source is an array. If it's a model, like in my case, the paginator object isn't created, only it's defined the limit for do the pagination.

**Comment by zofe** [comment]
I've tested on L5 and it works also with models,
as you can see here:
https://github.com/zofe/rapyd-laravel/blob/master/src/DataSet.php#L210
paginator is filled also with model  or query builder sources.

**Comment by farynato** [comment]
I don't know but in my case paginator is null, after I call paginate. I thought that the reason was the different code when the source is an array (the object LengthAwarePaginator is created) or a query/model (is only an assignment using the limit of pagination). Anyway I found an alternative solution. Thank you for your help.
