### ISSUE TITLE
Date field default value

### ISSUE THREAD

**Issue by kingomalek** [zofe/rapyd-laravel#164]
Hi , i have a problem when using date fiel
i doesnt  take default value

whenei use for example
$form = DataEdit::source( Experience::find($id));
$form->add('start', 'Start', 'date')->attributes(['required' => 'required']);

date field dont take the current value in DB.

is there any solution or explanation .

**Comment by kingomalek** [comment]
So i removed from Date.php , this part : "case:modify"

 if ($this->value != "") {
                    if (!$this->is_refill) {
                        $this->value = $this->isoDateToHuman($this->value);
                    }
                }

The problem is solved .

**Comment by farynato** [comment]
@zofe I have the same problem, is it an error?

**Comment by zofe** [comment]
@kingomalek  editing "vendor folder"  is a wrong thing, don't do that.  
@farynato  as you can see here: http://www.rapyd.com/rapyd-demo/edit?modify=1
date field is working.

About date field format it's used only for "visualization", rapyd and most DBMS assume a date in the iso standard (Y-m-d).  So  you can use format() as explained here:
https://github.com/zofe/rapyd-laravel/wiki/Field-list
 
About "default values" you can read about here:
https://github.com/zofe/rapyd-laravel/wiki/Default-values
 
Note: if you set a default value for a date field, rapyd assume it as iso date (so: Y-m-d)  even if you use different format() for visualization.  So you can :
```php
$form->add('start', 'Start', 'date')->format('d/m/Y','it')->insertValue(date('Y-m-d));
```
- this mean  add a date field,  
- use d/m/y format to display it and use Italian language for calendar, 
- by default the value to be stored in the db  should be  Y-m-d.

**Comment by farynato** [comment]
@zofe You were right. I had two get methods in the model class that were in conflict while retrieving the dates. Thank you very much and sorry for your time.
