### ISSUE TITLE
getting filtered list with DataGrid

### ISSUE THREAD

**Issue by rpg999** [zofe/rapyd-laravel#166]
I have read the documentation and i found that there is 2 ways to create data grid

```
DataGrid::source(User::with('tags'))
```
or
```
DataGrid::source(new User));
```

But how can i get the filtered list of user, for example if i am admin , i want to see the list of all users, but if I am director , i can see the list of managers only ?

**Comment by zofe** [comment]
this is not related with DataGrid,  is related to your source, so your model.
you can get it  using a query scope to your source, before passing it to the datasource.

something like:
`
$source = User::with('tags');
if (Auth::user()->role == 'director') {
    $source->where('role','!=','admin');
}
DataGrid::source($source);

`

**Comment by rpg999** [comment]
thank you .
