### ISSUE TITLE
DataEdit question and suggestion

### ISSUE THREAD

**Issue by Game59** [zofe/rapyd-laravel#167]
Can't I desable de "show=" after validating a form ? I Wanna allow the user just to upload files for exemple, and after validating the form for that, to redirect him somewhere else ( by default (now) the user after completing the Dataedit form is automaticly redirect in the "show=id") .
And i suggest you to create this : $edit->add('documents','Documents', 'fileS'), for multiupload ! That's will make things easyer !

Thanks for your work, you're a beast !

**Comment by tacone** [comment]
Hello, did you try to add 'back()`?

Take a look to the DataEdit demo, for instance: http://www.rapyd.com/rapyd-demo/edit
```php
$edit->link("rapyd-demo/filter","Articles", "TR")->back();
```
If you do that, it will redirect to `rapyd-demo/filter` right after saving.

As for the second suggestion, it seems to be a won't do for now https://github.com/zofe/rapyd-laravel/issues/154.

**Comment by Game59** [comment]
Thanks a lot for your fast reply ! All works good now and my problem is FIXED so ! 
Props for you
