### ISSUE TITLE
wrong date if year is from another century

### ISSUE THREAD

**Issue by jmcerrejon** [zofe/rapyd-laravel#168]
I'm using Laravel 4.2

I tried in the demo (and in my code)  to change in a date field, the year with for example, 1475. The result:

In the datagrid **show 30/11/-0001**

In the dataedit, **the field is blank**.

I can change the value in the table directly and the datagrid show the right date.

All works like a charm if the year is over 2000.

**Removing the datepicker plugin does not fix the problem.**

I'm using the next code:

Datagrid:
...
_$grid=DataGrid::source(TimeLine::find('1'));_
_$grid->add('fecha|strtotime|date[d/m/Y]','Fecha', true);_
...

DataEdit:
...
_$edit=DataEdit::source(new TimeLine());_
_$edit->add('fecha','Fecha','date')->attr('class','my_datepicker')->format('d/m/Y', 'es');_
...

**Comment by jmcerrejon** [comment]
I think the issue is in the format *"d-m-Y"*.

**Comment by zofe** [comment]
Im not sure that strtotime() works with a date < 1970 
if it works the result should be a negative number.. then the problem can be date() with a negative timestamp.

**Comment by davelopware** [comment]
http://stackoverflow.com/questions/2871264/using-strtotime-for-dates-before-1970

**Comment by jmcerrejon** [comment]
strtotime() & Datagrid is OK, The problem is when save the Dataedit. Where Can I see it in the code?

**Comment by jmcerrejon** [comment]
The problem is a misunderstood with the format: Using Y-m-d in the field, works like a charm. But when I change it with another format (d-m-Y), fail. Maybe calling a method before click on the Save button, do the magic...

Thank you.
