### ISSUE TITLE
Interesting naming issue

### ISSUE THREAD

**Issue by zhouyi531** [zofe/rapyd-laravel#169]
Hi there,

I'm new to rapyd but it's amazingly useful while I just want to build up a simple CRUD back end!

But I met one strange issue while using edit:

````
$edit->addSelect('PropertyType','物业类型')->options([''=>'--选择--','公寓'=>'公寓','别墅'=>'别墅','商铺'=>'商铺','写字楼'=>'写字楼']);
````
The 'PropertyType' is varchar(255)	utf8_unicode_ci field in mysql. This will never work unless I rename the field to something else like I removed the last 'e' to PropertyTyp and it worked.

I got another field called 'BuildingType' and it's the same case so I'm quite convinced the issue was caused by the naming thing. Look forward to your reply. Thanks a lot!

**Comment by zofe** [comment]
"will never work"  means it throw an error or is just ignored on save?

**Comment by zhouyi531** [comment]
Hi zofe,

Sorry for the late response. Yes I tried and I suppose it's some cache thing because after I restarted the server and rename the fields to previous with 'type' as the postfix and it worked this time.

Thanks very much!

Austin
