### ISSUE TITLE
Same result on 2 different DataGrid after filtering

### ISSUE THREAD

**Issue by Tarrtar** [zofe/rapyd-laravel#171]
Hello, i have created 2 different DataSets with 2 different DataFiters that placed on 2 different JQuery Tabs but when i make a search with one of these DataFilters it effects both of the DataGrids. How can i fix it ? Thanks.

**Comment by zofe** [comment]
ok undocumented stuff so I must explain:
- DF+DG  must share the same  "cid"  component-id
- When you instance a DG (or DS)  from a datafilter source  this "sharing" is done by default:
https://github.com/zofe/rapyd-laravel/blob/master/src/DataSet.php#L53

So "search"  and "orderby"  should work properly (on each df+dg pool).
But  there is a problem, pagination will not work  "splitted" on each pool, this problem is  "laravel related", since we can't customize "pag" param in laravel (to use for example "pag2" for the second pagination).

if anyone know if laravel API allows us to manage  "pag" param for pagination, please let me know.

**Comment by tacone** [comment]
It is probably this:

http://laravel.com/api/4.2/Illuminate/Pagination/Factory.html#method_setPageName
http://laravel.com/api/5.0/Illuminate/Pagination/Environment.html#method_setPageName

**Comment by Tarrtar** [comment]
I am trying to create 2 different filters and datagrids with same data model. When i make a search both of my datagrids show the same result and i do not want this. I dont have any problems with pagination.

**Comment by tacone** [comment]
Post your code so we can take a look.

**Comment by Tarrtar** [comment]
public function createSearchFilter()
    {
        $searchFilter = DataFilter::source(new Vehicle);
        $searchFilter->attributes(array('class'=>'form-inline'));
        $searchFilter->add('id','Evrak No', 'text')->attr('class','textbox');
        $searchFilter->add('Plaka','Plaka', 'text')->attr('class','textbox');
        $searchFilter->add('Marka','Marka', 'text')->attr('class','textbox');
        $searchFilter->add('Model','Model', 'text')->attr('class','textbox');
        $searchFilter->add('adsoyad','Ad-Soyad', 'text')->attr('class','textbox');
        $searchFilter->add('il','İl', 'text')->attr('class','textbox');
        $searchFilter->add('AracNerde','Araç Nerde', 'text')->attr('class','textbox');
        $searchFilter->add('sasemotor','Şase/Motor', 'text')->attr('class','textbox');
        $searchFilter->add('vekalet','Vekalet', 'text')->attr('class','textbox');
        $searchFilter->add('takas','Takas', 'text')->attr('class','textbox');
        $searchFilter->submit('Ara');
        $searchFilter->reset('Sıfırla');
        $searchFilter->build();

        return $searchFilter;
    }


    public function createVehicleTrackFilter() 
    {
        $vehichleTrackFilter = DataFilter::source(new Vehicle, new Song);
        $vehichleTrackFilter->attributes(array('class'=>'form-inline'));
        $vehichleTrackFilter->add('saseNo','Şase No', 'text')->attr('class','textbox');
        $vehichleTrackFilter->add('Plaka','Plaka', 'text')->attr('class','textbox');
        $vehichleTrackFilter->submit('Ara');
        $vehichleTrackFilter->reset('Sıfırla');
        $vehichleTrackFilter->link('pages/deneme', 'YAZDIR');
        $vehichleTrackFilter->build();

        return $vehichleTrackFilter;
    }

public function createVehicleDataGrid($dataSource) {
        $searchGrid = DataGrid::source($dataSource);
        $searchGrid->add('id','Evrak No', true)->style('width:150px;');
        $searchGrid->add('AlisTarihi','Alış Tarihi', true)->style('width:150px;');
        $searchGrid->add('Model','Model', true)->style('width:150px;');
        $searchGrid->add('Marka','Marka', true)->style('width:150px;');
        $searchGrid->add('Plaka','Plaka', true)->style('width:150px;');
        $searchGrid->add('Alinan','Alınan Kişi', true)->style('width:150px;');
        $searchGrid->add('ATel','ATEL', true)->style('width:150px;');
        $searchGrid->add('AlinanYer','Alınan Yer', true)->style('width:150px;');
        $searchGrid->add('RuhsatSahibi','Ruhsat Sahibi', true)->style('width:150px;');
        $searchGrid->add('TN','TN', true)->style('width:150px;');
        $searchGrid->add('AlisTakas','Alış-Takas', true)->style('width:150px;');
        $searchGrid->add('SatisTarih','Satış Tarihi', true)->style('width:150px;');
        $searchGrid->add('SattigimizKisi','Satılan Kişi', true)->style('width:150px;');
        $searchGrid->add('SatilanYer','Satılan Yer Yer', true)->style('width:150px;');
        $searchGrid->add('STel','STEL', true)->style('width:150px;');
        $searchGrid->add('TakasNo','Takas No', true)->style('width:150px;');
        $searchGrid->add('TakasAdi','Takas Adı', true)->style('width:150px;');
        $searchGrid->add('AracNerde','Araç Nerede', true)->style('width:150px;');
        $searchGrid->add('EvrakHazir','Evrak Hazır Mı?', true)->style('width:150px;');
        $searchGrid->add('YeniEvrak','Yeni Evrak Mı?', true)->style('width:150px;');

        $searchGrid->paginate(4);
        //$searchGrid->build();
        
        $searchGrid->row(function ($row) {
           if ($row->cell('id')->value % 2 == 0) {
               $row->style("background-color:#CCFF66");
           } 
        });
        
        return $searchGrid;
    }
    
    public function createVehicleTrackDataGrid($dataSource) {
        $vehicleTrackDataGrid = DataGrid::source($dataSource);
        $vehicleTrackDataGrid->add('id','Evrak No', true)->style('width:150px;');
        $vehicleTrackDataGrid->add('AlisTarihi','Alış Tarihi', true)->style('width:150px;');
        $vehicleTrackDataGrid->add('Model','Model', true)->style('width:150px;');
        $vehicleTrackDataGrid->add('Marka','Marka', true)->style('width:150px;');
        $vehicleTrackDataGrid->add('Plaka','Plaka', true)->style('width:150px;');
        $vehicleTrackDataGrid->add('Alinan','Alınan Kişi', true)->style('width:150px;');
        $vehicleTrackDataGrid->add('ATel','ATEL', true)->style('width:150px;');
        $vehicleTrackDataGrid->add('AlinanYer','Alınan Yer', true)->style('width:150px;');
        $vehicleTrackDataGrid->add('RuhsatSahibi','Ruhsat Sahibi', true)->style('width:150px;');
        $vehicleTrackDataGrid->add('TN','TN', true)->style('width:150px;');
        $vehicleTrackDataGrid->add('AlisTakas','Alış-Takas', true)->style('width:150px;');
        $vehicleTrackDataGrid->add('SatisTarih','Satış Tarihi', true)->style('width:150px;');
        $vehicleTrackDataGrid->add('SattigimizKisi','Satılan Kişi', true)->style('width:150px;');
        $vehicleTrackDataGrid->add('SatilanYer','Satılan Yer', true)->style('width:150px;');
        $vehicleTrackDataGrid->add('STel','STEL', true)->style('width:150px;');
        $vehicleTrackDataGrid->add('TakasNo','Takas No', true)->style('width:150px;');
        $vehicleTrackDataGrid->add('TakasAdi','Takas Adı', true)->style('width:150px;');
        $vehicleTrackDataGrid->add('AracNerde','Araç Nerede', true)->style('width:150px;');
        $vehicleTrackDataGrid->paginate(4);
        //$vehicleTrackDataGrid->build();
        
        return $vehicleTrackDataGrid;
    }

//calling functions

public function aracislemler()
	{
            //$dataSource = DB::table('vehicles')->join('clients', 'vehicles.id', '=', 'clients.id')->get();
            $rapydProcess = new RapydController();
            $searchFilter = $rapydProcess->createSearchFilter();
            $searchGrid = $rapydProcess->createVehicleDataGrid($searchFilter);
            $vehicleTrackFilter = $rapydProcess->createVehicleTrackFilter();
            $vehicleTrackDataGrid = $rapydProcess->createVehicleTrackDataGrid($vehicleTrackFilter);

            return view('pages.aracislemler', compact('searchFilter', 'searchGrid', 'vehicleTrackFilter', 'vehicleTrackDataGrid'));
	}

**Comment by zofe** [comment]
@Tarrtar a request for you, (next time post less code,  and use github formatting :
https://help.github.com/articles/github-flavored-markdown/
I've just cleaned a bit  (removing some unneeded field, "unneeded" to understand the problem).

- You used this syntax:  DataFilter::source(new Vehicle, new Song);
but DataFilter source accept only one parameter:
https://github.com/zofe/rapyd-laravel/blob/master/src/DataFilter/DataFilter.php#L29

- At this moment i don't see any error but is the first time I see this kind of encapsulation, aracislemler() is in the same RapydController() ?  

- However I've tested the code I posted to you, and it work (except for pagination).

@tacone thanks  for the tip,  I'll fix the multiple pagination issue using setPageName from the api.

**Comment by Tarrtar** [comment]
@zofe sorry for my rawness as a newbie and thanks for your reply. I have corrected the DataFilter syntax and still getting the same issue. aracislemler() function is in a different controller(PagesController) which i manage page requests and creating/passing Rapyd components to necessary view.

**Comment by Tarrtar** [comment]
It appears to be only one form when i inspect my html but there are 2 filters,i think that might cause that issue but i am not sure. It suppose to be 2 forms for each DF i guess or i am wrong ?

**Comment by zofe** [comment]
you've a customized form output or just :
       
        {!! $filter !!}
        {!! $grid !!}

        {!! $filter2 !!}
        {!! $grid2 !!}

**Comment by Tarrtar** [comment]
i ve done it as you mentioned above

**Comment by zofe** [comment]
"It appears to be only one form"  means  the same form 2 times  or one of them is empty?

**Comment by Tarrtar** [comment]
Just one form that returns same string for both filters

**Comment by Tarrtar** [comment]
My search result still effects both of my DataGrids and can not solve this problem. Anybody has an idea about it ?

**Comment by zofe** [comment]
try using 
return $searchGrid->output   
instead of $searchGrid

**Comment by Tarrtar** [comment]
Grid disappears

**Comment by zofe** [comment]
too complex to evaluate your code.
on 5.1 now rapyd has the dataembed  widget to do this kind of stuff:
http://www.rapyd.com/rapyd-demo/embed
