### ISSUE TITLE
Bug ? ->mode('readonly');

### ISSUE THREAD

**Issue by Game59** [zofe/rapyd-laravel#174]
hi, here is the line : 
$form->text('id','Transaction ID')->mode('readonly');
and when the form is saved, the id take automaticly the value 0; 
Logicaly the error : 
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY' 

I can simply delete it and all work but maybe I'm doing something wrong ?! I just wanted the Transaction ID to be showed

**Comment by zofe** [comment]
It's not a bug, read means just not user-editable field, it doesn't mean that it will be autogenerated.
To proper manage a default value you can use insertValue(), updateValue()  as explained in the wiki.

Example of custom logic for a primary key using a custom method in the model:
  
    $edit->add('ID', 'ID', 'auto')->insertValue($edit->model->generateID());
