### ISSUE TITLE
gif image

### ISSUE THREAD

**Issue by AntonBenediuk** [zofe/rapyd-laravel#178]
Sorry but I have another problem.I can't upload gif image from DataGrid. I try chage rule butt still can upload gif.

**Comment by zofe** [comment]
https://github.com/zofe/rapyd-laravel/blob/master/src/DataForm/Field/Image.php#L12

this means by default  we assume ->rule("mimes:jpeg,png");
you need just to use ->rule("mimes:jpeg,png,gif");

**Comment by AntonBenediuk** [comment]
I try:
$form->add('gerb','Gerb', 'image')->move(public_path().'/assets/images/university/')->rule('mimes:jpeg,png,gif')->fit(240, 160)->preview(120,80);
but still ' validation.mimes'. Where is problem?
