### ISSUE TITLE
Center alignment for buttons

### ISSUE THREAD

**Issue by farynato** [zofe/rapyd-laravel#181]
Would it be possible can choose center alignment for buttons in DataEdit (maybe using class center-block instead of pull-right or pull-left in divs)? Could you add it?

**Comment by zofe** [comment]
no, I'm sorry  no time for this,  and in "bootstrap terms"  to have 3 positions (left center right)  can be only  obtained using the grid sistem,  so row + col-x * 3.  Too complex,  I prefer to keep  pull-left / pull-right.
