### ISSUE TITLE
Different behaviour undo button in DataEdit

### ISSUE THREAD

**Issue by farynato** [zofe/rapyd-laravel#182]
When I have only undo button in DataEdit, it's linking to show action of the element ('.../edit?show=1') but when I have other button like this:
$edit->link("colonias/ratones/list","Listado", "TR")->back();
undo button is linking to the same route that the other button ('colonias/ratones/list'). I don't understand this.

Anyway, is it possible to eliminate undo button from DataEdit form? I think I wouldn't need it.

**Comment by zofe** [comment]
https://github.com/zofe/rapyd-laravel/wiki/DataEdit#back-action

**Comment by farynato** [comment]
Ok, it's not possible to eliminate the button, but what about the different behaviour of the undo button when there is another button? Is this correct?

**Comment by farynato** [comment]
Another curious thing is that I have the same line of code for a button link in DataEdit than you have in your example code of DataEdit and I obtain the button specified and also undo button. In your example doesn't appear undo button. I can't explain this.

I have: 
$edit->link("colonias/ratones/list","Listado", "TR")->back();

**Comment by farynato** [comment]
@zofe Sorry for my insistence. Have you some knowledge or suggestion about this?
