### ISSUE TITLE
Class \Zofe\Rapyd\Controllers\AjaxController does not exist

### ISSUE THREAD

**Issue by davelopware** [zofe/rapyd-laravel#183]
I'm getting Server 500 errors with "Class \Zofe\Rapyd\Controllers\AjaxController does not exist" for the autocomplete fields.

Looks like it's because the vendor/zofe/rapyd/src/**c**ontrollers directory has a lower-case 'c'. If I manually change it to be an upper-case 'C' then it all works fine. Note I'm running on Ubuntu 14.04 with apache.

Fix - rename:

    vendor/zofe/rapyd/src/controllers

to

    vendor/zofe/rapyd/src/Controllers

**Comment by zofe** [comment]
from psr-4 spec.:
- The subdirectory name MUST match the case of the sub-namespace names.
so my fault.
I'll fix thanks.
