### ISSUE TITLE
Rapyd not redirect to list if saved() function is overided

### ISSUE THREAD

**Issue by rpg999** [zofe/rapyd-laravel#185]
to change some value before saving object, i overided Eloquent save() function to something like that
```
public function save(array $options = array())
    {
        $this->url_page = strtolower(str_replace(' ', '-', $this->title_page));

        parent::save();
    }
```

after that when is press `Save` button in the form, the object will be saved or updated to the DB , but rapyd not redirects me to the list.
When i remove overrided save function , everything works fine.

**Comment by zofe** [comment]
you should not override save,  you can use http://laravel.com/docs/5.0/eloquent#model-events
As you can see in demo models http://www.rapyd.com/rapyd-demo/models I've used to preserve integrity on deleting  (search deleting  or boot)

**Comment by rpg999** [comment]
Thank you for you answer. By the way , can you tell me how can i set the path for uploading file for redactor in Rapyd ?

**Comment by zofe** [comment]
I suggest you to use a custom version of redactor. Switch:

    $form->add('body','Body', 'redactor'); //from
    $form->add('body','Body', 'textarea')->attr('class','redactor'); //to
 
include your redactor copy where you want, and then you can customize buttons, upload integration etc.
Redactor upload integration is not supported in rapyd and redactor wysiwyg itself will be abandoned soon

**Comment by rpg999** [comment]
Thank you vary much.
