### ISSUE TITLE
Autocomplete not obligatory

### ISSUE THREAD

**Issue by farynato** [zofe/rapyd-laravel#189]
I have a question:
Is there any way using autocomplete fields in DataEdit where the suggestion choice isn't obligatory? That is, you can enter other value different to suggestions and this value can be saved in BD.
Thanks in advance.

**Comment by farynato** [comment]
I have realized that by default autocomplete fields don´t support entering other different values to the suggestions due to the typeahead construction for the fields.
In https://github.com/zofe/rapyd-laravel/blob/master/src/DataForm/Field/Autocomplete.php#L166 and https://github.com/zofe/rapyd-laravel/blob/master/src/DataForm/Field/Autocomplete.php#L205, when it's defined **typeahead:closed**, it's not permitted a value different to suggestions, it will be considered like an empty string.

                     }).on("typeahead:closed",
                        function (e,data) {
                            if ($(this).val() == '') {
                                $('#{$this->name}').val('');
                            }
                    });

I think it would be interesting to add the possibility for some autocomplete fields to enter other values typed by users. One posible solution would be something like this...

                     }).on("typeahead:closed",
                        function (e,data) {
                            if ($(this).val() == '') {
                                $('#{$this->name}').val('');
                            }
                            else{
                                var myVal = $('#auto_{$this->name}').val();
                                $('#{$this->name}').val(myVal);
                            }
                    });

...with some flag option to indicate the necessity of adding the code for the autocomplete field.
What do you think about it?

**Comment by zofe** [comment]
at this time i can't follow and test this kind of stuff but you can:

- fork and test this on your branch, stay on your branch to be free to "fix" and be "productive" but then you have to merge mainstream changes manually.
when you're sure that the fix does not broke backward compatibility of demo you can make a pull request.

- make a custom field https://github.com/zofe/rapyd-laravel/wiki/Creating-Fields  if this problem is only related to the form field you're trying to customize

**Comment by farynato** [comment]
Finally I made a custom field with the modifications I commented previously but maybe it could be interesting to improve Autocomplete field with this in the future. Thank you!

**Comment by zofe** [comment]
good job @farynato
