### ISSUE TITLE
Datasource from an array, stdclass object or a json/xml RESTful API

### ISSUE THREAD

**Issue by Maykonn** [zofe/rapyd-laravel#190]
Is possible set datasource from an array stdclass object or a RESTful API call:

```
DataGrid::source('http://myapi.com/users');
```

```
DataGrid::source([]);
```

```
DataGrid::source(json_decode('[{}]'));
```

**Comment by zofe** [comment]
since it works  with multidimensional arrays, it is possible to bind  something like:

    DataGrid::source((array)json_decode(file_get_contents('http://myapi.com/users')))

untested

**Comment by Maykonn** [comment]
I'm getting invalid data provider.

**Comment by Maykonn** [comment]
Ok, thanks!

**Comment by zofe** [comment]
i think you can do:
DataGrid::source(json_decode(file_get_contents('http://myapi.com/users',true)))

**Comment by Maykonn** [comment]
Yes, it works fine. I write wrappers for my external API, that make requests using Guzzle:

```
\DataGrid::source(\External::call('/search/pagination/10,0/sort/desc', \Request::GET)->getResponseBodyAsArray());
```

Now I will implement pagination, sort, etc.
Thanks @zofe!

**Comment by Maykonn** [comment]
@zofe When I try to add a column from multidimensional array:

```
$grid->add('title','Title', true);
$grid->add('category.name','Category', true); 
```

The title column is ok, but the category.name is write as 'category.name' instead the product category name.

**Comment by zofe** [comment]
the dot syntax  is translated as "relation.fieldname",  you should find an alternative: 
using alias api-side or "blade syntax" on server-side https://github.com/zofe/rapyd-laravel/wiki/DataGrid

**Comment by Maykonn** [comment]
Sorry, but I don't understand:
```
maybe {{ $row['category.name'] }} ?
```

I'm try to make it, but not work, I think that I don't understand =):
```
$grid->add("{{$row['category.name']}}",'Category', true);
```

**Comment by zofe** [comment]
try to change the problematic key in your resultset:  something like:
´´´php
$rows = json_decode(file_get_contents('http://myapi.com/users'),true);
$rows = array_map(function($row) {
    $cleanrow = $row;
    $cleanrow['category_name'] = $row['category.name'] ;
    return $cleanrow;
}, $rows);
```
then you can use `$grid->add("category_name",'Category', true);`

**Comment by Maykonn** [comment]
I will write a layer to translate the API incompatible responses to app core(a wrapper for my \External call responses). Thanks!
