### ISSUE TITLE
do not waste time build your admin with rapyd!  why?

### ISSUE THREAD

**Issue by serverfire** [zofe/rapyd-laravel#196]
In wiki said "do not waste time build your admin with rapyd! "

Why ?

**Comment by zofe** [comment]
I think  missed a comma before "build"..  
but I meant  "use someting that is ready to use for your adimins.. do not reinvent the wheel"

**Comment by serverfire** [comment]
@zofe  I think you should let them use it for whatever they want .
If this package have problem with Auth or anything related to admin you can warn them , otherwise please remove that, you have done amazing work with that your losing your users .

**Comment by zofe** [comment]
@serverfire ok.. 
you'll like this even less  https://github.com/zofe/rapyd-laravel/wiki
:)

**Comment by serverfire** [comment]
@zofe  thank you
