### ISSUE TITLE
Data Grid null value appears as {{$seller->full_name}}

### ISSUE THREAD

**Issue by Tarrtar** [zofe/rapyd-laravel#197]
I am trying to display some data in grid it is defined as
 ```$searchGrid->add('seller.full_name','Alınan Kişi', true); ``` 
I display it by using Laravel relationship but if the field is null in the database it appears like 
 {{$seller->full_name}}  in the grid. I put this accessor to necessary model but it does not effect empty fields just changes non-empty fields

```
    public function getFullNameAttribute($value)
    {
        if ($value == null) {
            return '';
        }else{
            return $value;
        }
        
    } 
```

 How can i fix this ? Any help would be appreciated.

**Comment by zofe** [comment]
$searchGrid->add('seller.full_name','Alınan Kişi', true); 

1. youcan't order by related field so you should omit the third param.
2. relation.fieldname can be expressed  also as blade syntax.. this is a old issue where you can find a solution using  blade:
https://github.com/zofe/rapyd-laravel/issues/75  
tell me it it solve

**Comment by Tarrtar** [comment]
I tried it as ```{{$row->seller->full_name }}``` null values still appear the same

**Comment by Tarrtar** [comment]
{{@$seller->full_name }} works, thanks

**Comment by zofe** [comment]
good
