### ISSUE TITLE
Call to undefined method Zofe\Rapyd\DataGrid\Column::cell()

### ISSUE THREAD

**Issue by fabinou** [zofe/rapyd-laravel#199]
Hello,

I am using laravel 4.2 and the package is working rather well except when i try to do this : 
$grid = DataGrid::source($filter);
   $grid->add('custom','Custom')->cell(function ($value) {
       // you can do for example format $value and/or
        return 'custom.. code or view';
    });

I get Call to undefined method Zofe\Rapyd\DataGrid\Column::cell()

I load use Zofe\Rapyd\Facades\DataGrid in my controller but with no success.

What am i doing wrong ?

Thanks for any help

**Comment by zofe** [comment]
as you can see from samples  cell is available  inside row closure,  not as method of column object

**Comment by fabinou** [comment]
well ... i feel so dumb ... sorry to have bother you and thanks a lot
