### ISSUE TITLE
DataGrid altering documentation fro Laravel 5.1

### ISSUE THREAD

**Issue by stephenahiggins** [zofe/rapyd-laravel#205]
Hi, 

I have been trying to make the DataGrid function with Laravel 5.1. 
I eventually realised that the syntax is slightly different in Laravel 5 (I'm quite new to Laravel).

Documentation Syntax: 
```
$grid = DataGrid::source(Article::with('author'));  //same source types of DataSet
...
View::make('articles', compact('grid'))
```

Should be? 
```
 $grid = DataGrid::source(new Author);  //same source types of DataSet
...
  return view('articles'', compact('grid'));
```

**Comment by zofe** [comment]
Rapyd is tested on 5.0,  not in 5.1 (it should work however)
`DataGrid::source(new Author);`  means get all articles.

`DataGrid::source(Article::with('author'));` means get all articles and eager load author relation for each article. What appens is that Eloquent ORM do another select statement using a  "WHERE IN" using the correct FK to get all authors. (This is most of cases better  than a join in terms of performances).

`View::make('articles', compact('grid'))`  is valid syntax for L4,  but for L5 is needed some stuff i.e.  Start with "\" ( "\View") it means  that the namespace is the application and not the controller..
but  view function is a commodity  in L5 
 
All questions seems more related to Laravel, 
I admit I need to cleanup a bit  the docs.. and I hope to test  the L5.1 relase to check it all is ok.

**Comment by stephenahiggins** [comment]
Thank you for this! 

It's cleared a few things up. Great project, it's saved me a lot of time!

**Comment by Rolice** [comment]
I would like first, to tank you for the great package!
I would be glad to get update with 5.1 support, because currently we cannot upgrade Laravel on one of our projects from 5.0 to 5.1, because of the strong dependency on Laravel 5.0.

**Comment by tacone** [comment]
@rolice is it just a matter of `composer.json` ?

**Comment by zofe** [comment]
support for 5.1 is ok,  and dev is on 5.1 since few months

**Comment by Rolice** [comment]
@tacone, @zofe, yes only version mismatch in the composer JSON. The package dependencies were for 5.0, but not 5.1 and this lead to error while upgrading.

Thank you
