### ISSUE TITLE
FatalErrorException in DataEdit.php line 81: Class name must be a valid object or a string

### ISSUE THREAD

**Issue by stephenahiggins** [zofe/rapyd-laravel#211]
Hi, 

I've been using Rapyd Laravel with no problems for a few weeks. It's made my life a whole lot easier! 

However, I'm coming up against the following when trying to edit one particular table. 
```
FatalErrorException in DataEdit.php line 81:
Class name must be a valid object or a string
```

Any help would be greatly appreciated.

Controller Function: 
```
public function edit()
    {
        $edit = DataEdit::source(Aspire_Threshold::with('organisation'));
        $edit->label('Edit Points Model');

        $edit->add('author_id','Author','select')->options(Organisation::lists('name', 'id'));
        $edit->add('name','Name');
        $edit->add('cat1','Category 1');
        $edit->add('cat2','Category 2');
        $edit->add('cat3','Category 3');
        $edit->add('cat4','Category 4');
        $edit->add('cat5','Category 5');
        $edit->add('cat6','Category 6');

        return view('frontend.aspire.CRUD.edit', compact('edit'));

    }
```

Model: 
```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Aspire_Threshold extends Model
{
    protected $table = 'aspire_thresholds';

    protected $fillable = array('name', 'organisation_id', 'cat1', 'cat2', 'cat3', 'cat4', 'cat5', 'cat6');

    public function organisation()
    {
        return $this->hasOne('App\Organisation', 'id', 'organisation_id');
    }

}
```

**Comment by tacone** [comment]
That class name is weird. Could you try to rename your class to `AspireThreshold` ?

**Comment by stephenahiggins** [comment]
I've tried renaming. Still the same thing. 
Very strange, it works fine on other Models.

**Comment by tacone** [comment]
I guess you're stuck to the old method: remove everything, and add a line per time. If you do and happen to find the issue, let us know!

**Comment by danypellerin** [comment]
I'm getting the same error, which I am not getting with other Models. Will come back with more info if I end up finding what is behind the issue.

**Comment by danypellerin** [comment]
The value of $this->model is null which causes the error. 

I'm also getting this error on create: 
FatalErrorException in DataEdit.php line 152: Call to a member function getKey() on a non-object

Which has the same source ($this->model = null)
($this->redirect = $this->url->remove('insert' . $this->cid)->append('show' . $this->cid, $this->model->getKey())->get();)

I'm pretty sure it has nothing to do with the model name (mine is EventsFlytyer which follows the standards).

**Comment by danypellerin** [comment]
So basically there is no issue. I made a mistake where I passed the wrong info to the DataEdit::source. To solve the problem you need to replace:

        $edit = DataEdit::source(Aspire_Threshold::with('organisation'));
with
        $edit = DataEdit::source(new Aspire_Threshold);

That should solve the problem.

**Comment by tacone** [comment]
Yes, right, apparently DataForm and DataEdit do not support the query builder as a source and you need to pass an actual Model to make it work. Perhaps rapyd should be less silent about invalid input.

Let's close this bug for now.

**Comment by zofe** [comment]
Confirm that dataedit::source expects only model. 
The query builder support is only on DataSet/DataGrid
