### ISSUE TITLE
Proposal : Fields for Json

### ISSUE THREAD

**Issue by kandran** [zofe/rapyd-laravel#214]
What do you think about adding a Json kind of field. So user you edit and show json in a more friendly form.

Show: a kind of array
Edit : several fields witch on submit make an array corresponding to the json representation

I can make the pull request if it's usefull

**Comment by zofe** [comment]
´´´
Edit : several fields witch on submit make an array corresponding to the json representation
´´´
checkboxgroup & tags fields works  "also" storing a serialized version (comma separated), this in case  you don't use a valid  many-to-many relation for the field.
Basically, each "multiple" field is internally "serialized/deserialized" 
https://github.com/zofe/rapyd-laravel/blob/master/src/DataForm/Field/Field.php

I'm not sure that enabling also a "json" serialization will be an easy stuff, but  you can start looking main Field class (and tags/checkboxgroup).

I'm sure that you can simply add some config/property to let getNewValue() store a json instead  a comma separated string.
