### ISSUE TITLE
scope in DataForm?

### ISSUE THREAD

**Issue by therosco** [zofe/rapyd-laravel#219]
Does DataForm support scope?

Is it possible to write something like:
```php
    $form->add('author.name','Author','autocomplete')->scope(
        function($query, $value){
            return $query->where('firstname','like','%'.$value);
        }
    )->search(array('firstname','lastname'));
```
?

**Comment by tacone** [comment]
Hello, would you please provide the error or misbehavior you are getting?

**Comment by zofe** [comment]
it should also accept simple query scope closure:
https://github.com/zofe/rapyd-laravel/blob/master/src/DataFilter/DataFilter.php#L94

**Comment by therosco** [comment]
@tacone ,
in case we modify the code above to
```php
    $form->add('author.name','Author','autocomplete')->scope(
        function($query, $value){
            throw new \Exception('Just a test');
            return $query->where('firstname','like','%'.$value);
        }
    )->search(array('firstname','lastname'));
```
we would not get any exception. This means that function in scope is newer called.

**Comment by zofe** [comment]
scope are on DataFilter  not on DataForm
