### ISSUE TITLE
DataFilter adding a closure to manipulate query

### ISSUE THREAD

**Issue by zofe** [zofe/rapyd-laravel#22]
DataFilter is good enough as is,  but in some cases  a closure on fields or main class can help  to build better/complex filters.
Another idea is to bind  datafilter with eloquent query-scopes.

Some Ideas:

``` php
$filter->add('search','Find Something', 'text')->scope(function ($query, $value)  {
      return  $query->whereRaw("MATCH(`title`, `descr`, `tags`) AGAINST (?)", array($value));  
});
```

Or eloquent query scope binding:

``` php
$filter = DataFilter::source(new Article);
$filter->add('search','Find Something', 'text')->scope("search");

..
class Article extends Eloquent 
{
  ...
  public function scopeSearch($query, $value) 
  {        
          return $query->whereRaw("MATCH(`title`, `descr`, `tags`) AGAINST (?)", array($value));  
  }
..
```

Note that $value,  it's not just  _Input::get('search');_  It is _$filter->field('search')->getValue();_
So  for  complex or multiple fields (like autocomplete, date, tags..)  it's  a pre-processed value.
For example  for a Date field  that use a custom format   $value is instead  a iso datestamp  Y-m-d, so ready to be used in queries.

**Comment by farynato** [comment]
I've also tried to add a date field in DataFilter and I've noticed that there is not an automatic conversion to Y-m-d to compare the value with DB, in contrast to daterange, where it exists. I think that date fields need a getValue function like datarange fields (https://github.com/zofe/rapyd-laravel/blob/master/src/DataForm/Field/Daterange.php#L15) to make this conversion. What do you think about this?

**Comment by zofe** [comment]
as said  in thread  to transform a date from "input" to the standard iso datestamp  the DateField must know your input format.
So  you must use format()  and be sure that your  format notation is supported by javascript datepiker:
https://github.com/zofe/rapyd-laravel/blob/master/src/DataForm/Field/Date.php#L72
http://bootstrap-datepicker.readthedocs.org/en/release/options.html#format

and documented  in the wiki, see date field:
https://github.com/zofe/rapyd-laravel/wiki/Field-list

**Comment by zofe** [comment]
if you're sure that you're working right   and DataFilter does not support Date field  open a new issue  and be  propositive about how to solve the problem.  (pull request, or  suggestions are welcome)

**Comment by farynato** [comment]
Sorry for not specify, but I'm using:
$filter->add('fecha_nacimiento','DOB','date')->format('d/m/Y', 'es')

I think that the format is supported, however, the query executed is:
select * from `ratones` where `fecha_nacimiento` LIKE '%05/05/2015%'

If I change the field to datarange, it works, so it's for this for I was saying about a getValue function in Date.php, like in Datarange.php

**Comment by zofe** [comment]
so please open a new issue,  I hope to fix asap

**Comment by farynato** [comment]
@zofe Ok, I will open a new issue I'll try to be propositive, but it's still a little difficult for me because I am a beginner in laravel. Thank you very much.
