### ISSUE TITLE
categories on demo not escaping

### ISSUE THREAD

**Issue by evercode1** [zofe/rapyd-laravel#220]
Hi guys.  I'm new, just pulled in rapyd-laravel and called rapyd-demo.  On the demo page, categories are not being escaped, instead it's showing:

{{ implode(", ", $categories->lists("name")) }S}

Probably a typo somewhere but I couldn't find it.  I'm using Laravel 5.1.11.

**Comment by zofe** [comment]
hi, rapyd is untested on L > 5.0  but  i'll try to check this issue

**Comment by zofe** [comment]
this is fixed  on L 5.1.1  
due to a change in Eloquent syntax  we need to add ->all()   at the end.
