### ISSUE TITLE
datetime field not working in edit

### ISSUE THREAD

**Issue by danypellerin** [zofe/rapyd-laravel#223]
In DataForm\Field\Datetime.php

in function isodatetimeToHuman
\dateTime::createFromFormat($this->format, $isodatetime); 

Returns false with valid input. 

For instance:
$edit->add('begin','Begin', datetime')->format('Y-m-d H:i', 'fr')->rule('required');

The field is not filled in the edit form. I fixed it by making a copy of dateTime (created a custom field) except I replaced:
$datetime = \dateTime::createFromFormat($this->format, $isodatetime);  
   with
$datetime = new Carbon($isodatetime); 

In functions:
isodatetimeToHuman and humandatetimeToIso

**Comment by hayat97** [comment]
@danypellerin solution works for me too in setting the value into the field but it does not follow the format set, i.e.: d/M/Y H:i. Instead it display the default Y-m-d H:i:s

thanks

**Comment by zofe** [comment]
I think I've fixed  this with this commit: https://github.com/zofe/rapyd-laravel/commit/c8a2d49559221c4dd8d95231fe736c17fd095911
however for the future I'll adopt Carbon to switch between formats.

important: `->format('Y-m-d H:i', 'fr')` is no more required, as you can see in the commit, a default format can be defined in rapyd  config file.
