### ISSUE TITLE
get sum avg max min ..

### ISSUE THREAD

**Issue by kamioon** [zofe/rapyd-laravel#225]
Hi,
i have two question:

1- How can i have sum,avg,max,min of current datagrid's column. For example i have "amount" field in database and i want to get "sum" of current datagrid (with filtered action).

2- Can i add custom row (no custom column) for display some thing like sum or avg?

**Comment by zofe** [comment]
1.  in many ways,  you can create a cusrom  "accessor"  (see eloquent documentation)  that make the computation  then use it in datagrid,  or use a blade syntax  to make  the computation using php functions: ´{{ max($field1, $field2) }}´ ... or using row and cell  closure to do more complex stuff (see datagrid demo in the wiki: https://github.com/zofe/rapyd-laravel/wiki/DataGrid)

2.  No, I'm sorry
