### ISSUE TITLE
how to change route Edit

### ISSUE THREAD

**Issue by chliguiy** [zofe/rapyd-laravel#226]
hi,
i want to change  this route 
Route::get('/edit'      , array('uses'=>'xxxxController@edit'    ,'as'=> 'editcategorie'  ));
to this :
Route::get('/edit/show'      , array('middleware'=>'admin:user','uses'=>'xxxxController@edit'    ,'as'=> 'editcategorie'  ));
@zofe

**Comment by zofe** [comment]
routing and filtering in generale is not related with rapyd.

your problem is the method.
As explained in the docs (see the wiki)  a dataedit  need to  deal with  many http methods  (not only the GET method you routed);
https://github.com/zofe/rapyd-laravel/wiki/DataEdit#routing-only-a-dataedit
