### ISSUE TITLE
Crop Image field

### ISSUE THREAD

**Issue by tacone** [zofe/rapyd-laravel#228]
So... I still think the image and file fields are wrong, because if you upload an image in a form with invalid fields, you will be brought back to the form to correct your submission, but the file fields will be empty and you will need to select the files again.

The good news is that a client of mine expressed the need to crop the image before saving. So in a bunch of weeks I may get the chance to create an ajax upload file widget (with drag zones and instant preview) as well as a crop functionality in it.

Before I do, some questions:
- is there any other feature needed with the file field?
- should the crop be destructive, or create a new image yet preserving the master?
- since the upload would be via ajax, should I block the user from navigating away by the default?

I guess the hardest part will be to properly link the ajax submission with the rest of the form. @zofe, have you ever did something similar?

**Comment by zofe** [comment]
1. Someone asked about some other helper about image field (try to look even closed issues  about "image").
2. is destructive, however there is a closure "image"  that you can use to do duplicates or additional stuff on the uploaded image etc.:
`
$form->add('photo','Photo', 'image')
      ->move('uploads/demo/')
      ->image(function ($image) {
   // $image is an instance of \Intervention\Image\ImageManagerStatic 
})->preview(120,80);
`
I think you can reach the needed behavior (file upload persistence using some if and this closure) 

3.  I do not know

**Comment by tacone** [comment]
Hello, my second question was not about the current behavior but what should I implement myself. I guess the destructive way is the most straightforward, since otherwise we would have two filename (master image and cropped image) and things would get hairy pretty quick.

**Comment by tacone** [comment]
Other questions:
- should I prepare a separate package or just submit a PR? (mind you, I need it to work on Laravel 4.2)
- should I replace the `file` and `image` fields or create new ones? (`ajaxFile` and `ajaxImage`)

**Comment by zofe** [comment]
- I switched development on 5.1,  I think is better to keep PR for 5.1 stuffs
- you should first consider to make custom fields https://github.com/zofe/rapyd-laravel/wiki/Creating-Fields, however at this moment "adding new" is a better choice for me.
- It's your choice

**Comment by tacone** [comment]
Ok, then I will put together a separate package for the 4.2 only, and submit a PR for the 5.1 in the case you think it can be valuable to have it in the core.

Regarding the 3rd point, shall this be included in the core, it would be not really my choice. Anyways think about it anyways, had you any suggestion, it would be valuable to me.

Thanks for now.

**Comment by tacone** [comment]
Hello, client rejected the project. Won't do.
