### ISSUE TITLE
Get the last inserted id from the DataEdit insert function

### ISSUE THREAD

**Issue by eaponiente** [zofe/rapyd-laravel#229]
I didn't saw this on the docs I don't know if this is possible using DataEdit not DataForm

I have a code like this

$edit = DataEdit::source(new Directory);
$edit->add('phonenumber', 'Phone Number','text');
        $edit->add('smsnumber', 'SMS Number', 'text');
        $edit->add('email', 'Email Address', 'text');

Below the form I need to get the inserted_id of that form in the database how can I do that?

Operation::find($edit->model->id) // this is not working the ID is returning null

**Comment by zofe** [comment]
it is good practice to write the solution you adopted or the mistake you made  (It can be of help to others)

**Comment by eaponiente** [comment]
Hi sorry bout closing the issue while the problem is still hanging. 

Actually I didn't solve the problem I just created an alternative but I still cannot get the ID of the result of insert.

**Comment by zofe** [comment]
First of all you should look at model "events" http://laravel.com/docs/5.1/eloquent#events
Probably you need to do some stuff after a "Directory" is created,  then the correct place can be using:
- the app service provider as described in laravel doc, or
- the model itself  i.e.:
```php
   //Directory model
   ....
    protected static function boot()
    {
        parent::boot();

        static::created(function ($directory) {
            do some stuff with $directory->id
        });
    }
```
- or the controller 
```php
    ...
    Directory::created(function ($directory) {
            do some stuff with $directory->id
     });
```

- or using $edit->saved closure (at the same way of DataForm)

**Comment by eaponiente** [comment]
@zofe Thank you very much for the very fast reply :+1:
