### ISSUE TITLE
Relational model in DataEdit

### ISSUE THREAD

**Issue by MehmetOzkose** [zofe/rapyd-laravel#231]
Hi! 
I have no problem with the relational model in DataGrid.

`$productsFilter =  \App\Products::with('categories');`
`$this->filter = \DataFilter::source($productsFilter);`
`$this->grid->add('{{@$categories->name}}' ,'Category name');`
   
But I want to pass the  `{{@$categories->name}}` in DataEdit  but these lines returns *NULL*  for `{{@$categories->name}}` value.

`$this->edit = \DataEdit::source(new Products());`
,
,
`$this->edit->add('{{@$categories->name}}' ,'Category name','text');`

So how can I pass the `{{@$categories->name}}` value to edit view?

Thank you.

**Comment by zofe** [comment]
you cant use blade syntax at the same way in DE.

if you need to edit the relation you must use the dot syntax: 'relation' or 'relation.field'
and the correct kind of field:
- if relation is "hasOne"  usually it can be a "text" field 
- if relation is "belongsToMany" usually it can be  "checkboxgroup" or "tags" with autocomplete
- if relation is "belongsTo"  usually it can be  a "select"

you should look at demo:
http://www.rapyd.com/rapyd-demo/form
http://www.rapyd.com/rapyd-demo/advancedform

- if you need only to "show" relation  without editing  you can use a 'container' field
that support blade syntax
http://www.rapyd.com/rapyd-demo/advancedform

**Comment by MehmetOzkose** [comment]
The ralation is belongsTo.

Actually i want to show the category for the product in edit view file by select.

`$options =\App\Categories::lists("name", "id")->all();`       `$options=array('categories.id'=>'categories.name')+$options;`

**Comment by zofe** [comment]
I do not understand the reason of the second line,  however you can also append single options directly for example and empty one:
->add('parent_id', 'Parent Category', 'select')->option("","")->options($options);

**Comment by MehmetOzkose** [comment]
I edited the page but no result. Still can't pass `categories.name`. I should be missing something.

`$this->edit = \DataEdit::source(new \App\Products());`
  `$options =\App\Categories::lists("name", "id")->all();
  $this->edit->add('parent_id', 'Parent Category', 'select')->option('categories.id','categories.name')->options($options);`

**Comment by zofe** [comment]
`$options =\App\Categories::lists("name", "id")->all();`
this return an array of categories  with field "name" as value and field "id"  as key i.e.:
 [1=> 'category 1', 
  2=> 'category 2',
  3=> etc...]

`->option('categories.id','categories.name')`
what this means?   rapyd can't evaluate this, it just take a new option with given strings ad key and value.

**Comment by MehmetOzkose** [comment]
##### Products table

 id|name|category_id
------------ | -------------|-------------
1 |  samsun s5 | 2

##### Categories table

 id|name
------------ | -------------
1 |  cat2 
2 |  mobile phones
3 |  cat3
4 |  cat4

in edit view page of samsung s5, categories in select should be like this:

`  <option value="1">cat2</option> `
`  <option value="2" `**selected**`>mobile phones</option> `
`  <option value="3">cat3</option>`
`  <option value="4">cat4</option>`

DataGrid 
`  $productsFilter =  \App\Products::with('categories'); `
` $this->filter = \DataFilter::source($productsFilter); `
			
`$this->grid = \DataGrid::source($this->filter);`
`$this->grid->add('id','Id','id');`
`$this->grid->add('name', 'Product Name');`
`$this->grid->add('{{@$categories->name}}' ,'Category name'); `

How should be the DataEdit?

Thanks for your patience  :)

**Comment by zofe** [comment]
//as in examples you can see in the demo you should use the FK:
$edit->add('category_id','Category','select')->options(\App\Categories::lists('name', 'id'));

**Comment by MehmetOzkose** [comment]
How can it be so easy  :)
Thank you very much, this works in laravel 5.1.
`$this->edit->add('`**category_id**`','Category','select')->options(\App\Categories::lists('name', 'id')->all());`
