### ISSUE TITLE
Consider adding a multiselect field

### ISSUE THREAD

**Issue by tacone** [zofe/rapyd-laravel#233]
I needed a multiselect field because the tags field had some problems:

- it allows to create new elements (whereas I needed to forbid it)
- it ignores where clauses in the relation method (this is a bug probably)

So I took the checkboxgroup field, that seemed to work very well, and had it spit out a multiselect instead.

You can find the code here: https://gist.github.com/tacone/035ac0eddeed92030659

Then I included select2 in my project (no need to add it to rapyd, really, it's just what I did), and with a simple `$("select").select2();` all the selects got a search field for free, the multi-selects became tags fields.

I suggest to include a multi-select field in the core.

**Comment by zofe** [comment]
done https://github.com/zofe/rapyd-laravel/commit/6830ce0657aa2c32682d981b1ef57fa0daa40c22,
I'll test select2 asap

**Comment by tacone** [comment]
Whoops, a little too fast. :smile: I forgot to point out that the code was developed for Laravel 4.2 in the old branch. I advice you to test it a little bit to make sure it works with `dev-master`.

Btw :+1:
