### ISSUE TITLE
Call to undefined method Zofe\Rapyd\DataFilter\DataFilter::with()

### ISSUE THREAD

**Issue by sonijoy** [zofe/rapyd-laravel#234]
Hi,
I want to filter details from a table where its status is zero.I tried like this
 $filter = \DataFilter::source(new \App\category);
        $filter->add('id','ID', 'text');
        $filter->add('description','Description','text');
        $filter->add('created_at','Created date','daterange')->format('m/d/Y', 'en');
        $filter->submit('search');
        $filter->reset('reset');
        $filter->build();

        $grid = \DataGrid::source($filter::with('parent'));
        $grid->add('id','ID', true)->style("width:100px");
        $grid->add('title','Title');
        $grid->add('description','Description');
......

Here i am getting the error Call to undefined method Zofe\Rapyd\DataFilter\DataFilter::with().Please help me to solve this

**Comment by tacone** [comment]
try:
```php
$filter = \DataFilter::source(\App\category::with('parent');
$grid = \DataGrid::source($filter);
```

**Comment by sonijoy** [comment]
Hi,

I have a doubt.Can we use angular js with this...
My problem is that

I have to dropdown box category and subcategory.The subcategory dropdown is
filled if we select only the category from category dropdown box..How to do
this in laravel...Hope your reply

Thank you
Soni Joy



On Mon, Oct 12, 2015 at 5:22 PM, tacone <notifications@github.com> wrote:

> try:
>
> $filter = \DataFilter::source(\App\category::with('parent');$grid = \DataGrid::source($filter);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zofe/rapyd-laravel/issues/234#issuecomment-147374319>.
>



-- 

*Warm regards,*
*Soni Joy*
Software Engineer

*Email*: soni@sparksupport.com <abey@sparksupport.com>  *| * *Skype*:
spark.soni

<http://www.sparksupport.com/>  <http://www.sparkmycloud.com/>
<https://www.facebook.com/sparksupport>
<http://www.linkedin.com/company/244846>  <https://twitter.com/sparksupport>3rd
Floor, Leela Infopark, Phase -2,Kakanad, Kochi-30, Kerala, India *Phone*:+91
484 6561696 , *Mobile*:91-8129270421.          *Confidentiality
Notice:* Information
in this e-mail is proprietary to SparkSupport. and is intended for use only
by the addressed, and may contain information that is privileged,
confidential or exempt from disclosure. If you are not the intended
recipient, you are notified that any use of this information in any manner
is strictly prohibited. Please delete this mail & notify us immediately at
info@sparksupport.com

**Comment by tacone** [comment]
I'm sorry, this is not supported by Rapyd, at the moment.

**Comment by sonijoy** [comment]
okey..
Thank you

On Tue, Oct 13, 2015 at 5:49 PM, tacone <notifications@github.com> wrote:

> I'm sorry, this is not supported by Rapyd, at the moment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zofe/rapyd-laravel/issues/234#issuecomment-147698777>.
>



-- 

*Warm regards,*
*Soni Joy*
Software Engineer

*Email*: soni@sparksupport.com <abey@sparksupport.com>  *| * *Skype*:
spark.soni

<http://www.sparksupport.com/>  <http://www.sparkmycloud.com/>
<https://www.facebook.com/sparksupport>
<http://www.linkedin.com/company/244846>  <https://twitter.com/sparksupport>3rd
Floor, Leela Infopark, Phase -2,Kakanad, Kochi-30, Kerala, India *Phone*:+91
484 6561696 , *Mobile*:91-8129270421.          *Confidentiality
Notice:* Information
in this e-mail is proprietary to SparkSupport. and is intended for use only
by the addressed, and may contain information that is privileged,
confidential or exempt from disclosure. If you are not the intended
recipient, you are notified that any use of this information in any manner
is strictly prohibited. Please delete this mail & notify us immediately at
info@sparksupport.com

**Comment by sonijoy** [comment]
Hi

I am in a trouble.
I have two table 'users' and 'user_details'. I am listing data from
user_detail table with the user_id.Instead of listing user_id from
user_details ,I want to display the user name from users table in the place
of user_id from user_details table..

(I need Joining of two tables users and user_details as data source)

How to do this??

Hope your reply.
Thanks in Advance



On Mon, Oct 12, 2015 at 5:22 PM, tacone <notifications@github.com> wrote:

> try:
>
> $filter = \DataFilter::source(\App\category::with('parent');$grid = \DataGrid::source($filter);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zofe/rapyd-laravel/issues/234#issuecomment-147374319>.
>



-- 

*Warm regards,*
*Soni Joy*
Software Engineer

*Email*: soni@sparksupport.com <abey@sparksupport.com>  *| * *Skype*:
spark.soni

<http://www.sparksupport.com/>  <http://www.sparkmycloud.com/>
<https://www.facebook.com/sparksupport>
<http://www.linkedin.com/company/244846>  <https://twitter.com/sparksupport>3rd
Floor, Leela Infopark, Phase -2,Kakanad, Kochi-30, Kerala, India *Phone*:+91
484 6561696 , *Mobile*:91-8129270421.          *Confidentiality
Notice:* Information
in this e-mail is proprietary to SparkSupport. and is intended for use only
by the addressed, and may contain information that is privileged,
confidential or exempt from disclosure. If you are not the intended
recipient, you are notified that any use of this information in any manner
is strictly prohibited. Please delete this mail & notify us immediately at
info@sparksupport.com
