### ISSUE TITLE
Two problems

### ISSUE THREAD

**Issue by IProSoft** [zofe/rapyd-laravel#237]
Hi

First: grat work with the code!

Second: how I can add array fields like field['info], fiels[data] like 
<input type="text" name="field['info]">
<input type="text" name="field['data]">
And how I can make this form fields not beeing saved with model ? 
Just make them sended with other form fields so I can use them before save to serialize them in one field ?

Third: is ther way to add filed without reload, for example after select change, or button : "add text field" ?

Regards Artur

**Comment by zofe** [comment]
- about using form without model binding  see:
https://github.com/zofe/rapyd-laravel/wiki/DataForm
and look at the create()  method
- about square brackets.. no problem you can use them on a form without model binding
- about dynamic (ajax)  stuffs on widgets,  there is only some ajax "field" (autocomplete etc.)  but nothing related with entire widget (like ajax pagination, client-side form building). I can only suggest to take a look at riotjs  and other javascript framework.

**Comment by IProSoft** [comment]
Ok, thanks for help.
