### ISSUE TITLE
DataGrid blade-syntax "{!!"

### ISSUE THREAD

**Issue by bonzai86** [zofe/rapyd-laravel#239]
You're checking just for "{{" in the field for blade syntax. You should look for "{!!" too. Usefull for showing html-controls (e.g. checkboxes).

Maybe allowing this feature in headers too?

**Comment by zofe** [comment]
approved,  I'll add a check here asap
https://github.com/zofe/rapyd-laravel/blob/master/src/DataGrid/DataGrid.php#L149

**Comment by zofe** [comment]
about headers..  if it has this level of complexity can be a good choice to use a custom blade view.

about checkbox column I'll try do do something in the core.
