### ISSUE TITLE
Override save button

### ISSUE THREAD

**Issue by caracatiza** [zofe/rapyd-laravel#242]
Hi! I'm trying to override the default save button to change its location. I do the following:
`$form->submit('Save', 'BR');`
but this only adds a new button (which is probably logical). 
How can I remove the standard button, that would not be displayed two identical buttons in two places?

**Comment by zofe** [comment]
take a look at config options you'll find button_position

**Comment by caracatiza** [comment]
I only see a `$form->button_container` on the link here https://github.com/zofe/rapyd-laravel/wiki/Custom-Form-Layout, but I can't remove the default save button from it: I use `unset($form->button_container['BL'])` or `$form->button_container['BL'] = []`, but the form built with the default save button (which is placed in the `$form->button_container['BL']`).

**Comment by zofe** [comment]
`take a look at config options`:
 I mean look at /config/rapyd.php in your laravel project you'll find this file
https://github.com/zofe/rapyd-laravel/blob/master/config/rapyd.php

**Comment by caracatiza** [comment]
Thank you, it solved the issue.

**Comment by hellloveyy** [comment]
How do you do it？ I made this deletion but i also saw the submit...   help!thank @caracatiza 
```php
config(['rapyd.data_edit.button_position' => '']);
```
