### ISSUE TITLE
Class 'Zofe\Rapyd\RapydServiceProvider' not found

### ISSUE THREAD

**Issue by erkin0007** [zofe/rapyd-laravel#243]
Hi, i am trying install rapyld-laravel packate
When i wrire "php artisan vendor:publish"
Console say "Class 'Zofe\Rapyd\RapydServiceProvider' not found"
thank you..

**Comment by zofe** [comment]
you should follow each step:
https://github.com/zofe/rapyd-laravel#install-in-laravel-51-50-4

2015-10-20 15:06 GMT+02:00 erkin0007 <notifications@github.com>:

**Comment by erkin0007** [comment]
@zofe 
Yes i followed all step.
my composer file
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
		"zofe/rapyd": "2.1.*"
		
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1"
		
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "pre-update-cmd": [
            "php artisan clear-compiled"
        ],
        "post-update-cmd": [
            "php artisan optimize"
        ],
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
	
}
I add Zofe\Rapyd\RapydServiceProvider::class, on provider array. And i use laravel 5.1
but php artisan vendor:publish code is return Class 'Zofe\Rapyd\RapydServiceProvider' not found .
I search rapyd folder and files on my project folder but i not found.
Sorry for my english. thanks in advance

**Comment by zofe** [comment]
1. please,  use github markdown syntax if you post code.
2. check if you are using Zofe\Rapyd\RapydServiceProvider::class  and NOT 'Zofe\Rapyd\RapydServiceProvider'
(bacause you're on laravel 5.1)

**Comment by erkin0007** [comment]
@zofe Thank you. I fixed. Problem is my computer. I installed my server
