### ISSUE TITLE
How  rapyd can filter data from data filter query ?

### ISSUE THREAD

**Issue by LuckyBirds** [zofe/rapyd-laravel#247]
I get data from sql query, bud when i start application  i get error
FatalErrorException in DataSet.php line 207: Call to a member function count() on array

It is my code:

 $end_date=date('Y-m-d');
 $start_date = date_sub(date_create($end_date), date_interval_create_from_date_string('13 days'));
DB::table('vw_app_split_count')->orderBy('date')->where('date','<=',$end_date)->where('date','>=', $start_date)->get();
$filter = DataFilter::source($query);   
$filter->add('date','Дата', 'date')->format('Y/m/d', 'en'); 
$filter->submit('search');
$filter->reset('reset');
$filter->build();
$grid = DataGrid::source($filter)

If i get grit  whith query:
$grid = DataGrid::source($filter->query)
grid work, but flter not filtering

**Comment by zofe** [comment]
when you do ->get()  you will obtain a "collection"   so it's no more a quer builder instance

just omit  the ->get()  part

**Comment by LuckyBirds** [comment]
I remove  ->get(), and get empty grid,
$query = DB::table('vw_app_split_count')->orderBy('date')->where('date','<=',$end_date)->where('date','>=', $start_date);

dd($query) return a query builder instance, but it is not contain data from database

Builder {#300 ▼
  #connection: MySqlConnection {#203 ▶}
  #grammar: MySqlGrammar {#205 ▶}
  #processor: MySqlProcessor {#206}
  #bindings: array:6 [▶]
  +aggregate: null
  +columns: null
  +distinct: false
  +from: "vw_app_split_count"
  +joins: null
  +wheres: array:2 [▶]
  +groups: null
  +havings: null
  +orders: array:1 [▶]
  +limit: null
  +offset: null
  +unions: null
  +unionLimit: null
  +unionOffset: null
  +unionOrders: null
  +lock: null
  #backups: []
  #bindingBackups: []
  #operators: array:26 [▶]
  #useWritePdo: false
}

**Comment by zofe** [comment]
you should build also the $grid..
try this syntax to be sure that the view will work with already built  output:

        ..
        $filter = $filter->getForm();
        $grid = $grid->getGrid();
        return view('my.view', ['content' => $filter . $grid]);

**Comment by LuckyBirds** [comment]
i did     $grid = $grid->getGrid();
after
dd($grid)
and get:

"""
<div class="btn-toolbar" role="toolbar">\n
\n
        <div class="pull-left">\n
        <h2></h2>\n
    </div>\n
            </div>\n
\n
\n
\n
<table class="table table-striped">\n
    <thead>\n
    <tr>\n
         </tr>\n
    </thead>\n
    <tbody>\n
            <tr>\n
                    </tr>\n
            <tr>\n
                    </tr>\n
            <tr>\n
                    </tr>\n
            <tr>\n
                    </tr>\n
            <tr>\n
                    </tr>\n
            <tr>\n
                    </tr>\n
            <tr>\n
                    </tr>\n
            <tr>\n
                    </tr>\n
            <tr>\n
                    </tr>\n
            <tr>\n
                    </tr>\n
            <tr>\n
                    </tr>\n
            <tr>\n
                    </tr>\n
            <tr>\n
                    </tr>\n
            <tr>\n
                    </tr>\n
        </tbody>\n
</table>\n
\n
\n

what i do wrong ?
please help.

**Comment by zofe** [comment]
can you post the entire DF è DG    from beginning to the end ?

**Comment by LuckyBirds** [comment]
public function split()
    {
       $query = DB::table('vw_app_split_count');
       $filter = DataFilter::source($query);   

        $filter->add('date','Дата', 'date')->format('Y/m/d', 'en'); 
        $filter->submit('search');
        $filter->reset('reset');
        $filter->build();
        
         
        $grid = DataGrid::source($filter); 
        $grid->attributes(array("class"=>"table table-striped"));
        $grid->orderBy('date','desc');
        $grid->paginate(14); //pagination

        $cont=view('split', compact ('filter','grid')); 
        return view('zreports', compact('cont')); 
    
    }

**Comment by zofe** [comment]
as I said you should "add"  some column to the DataGrid.
DataGrid doesn't do it for you.

**Comment by LuckyBirds** [comment]
Thank you very match !
I add grid name 
 $grid->add('date','DATE');

and get result.
I think that grid build all columns from query.
