### ISSUE TITLE
DataTree

### ISSUE THREAD

**Issue by tacone** [zofe/rapyd-laravel#251]
Hello,
I started today the development of a Tree widget. The widget at the least for the moment being, will extend the DataGrid to produce a sortable, nested, ordered list (`<ol>`).

For the JS part I will use the unmantained [Nestable](http://dbushell.github.io/Nestable/)
For the model part I will require the user to extend a [Baum](https://github.com/etrepat/baum) model.

I am currently developing the widget as a separate plugin for Laravel 4, but once I'm done I would happily send a pull request for it to be included in the master branch.

Let me know if there is any interest in this.

**Comment by zofe** [comment]
I'll try to make it work on L 5   seems interesting

**Comment by tacone** [comment]
I plan to use DB transactions. Would that be ok, is there any drawback?

**Comment by tacone** [comment]
Hello, this is the related repository. At the moment nothing works yet, I'll ping you again when I have something in my hands.

https://github.com/tacone/rapyd-datatree

**Comment by zofe** [comment]
so it's a widget  not a field,  let me know when is done

**Comment by tacone** [comment]
Yes it's a widget which should look and be used more or less like the datagrid.

At the moment it extends the datagrid, but it would be probably saner to extend the dataset.  There are some differences though:

- cannot and should not paginate
- cannot be ordered via order-by since the ordering is implicit in the hierarchy model
- it does not accept a query builder, a table or an empty model. It needs to be fed a `loaded` model (for instance `MyModel::find(4);`) which will act as the root of the tree.

I'll let you know for sure. I have a hard deadline next w/e, so I have to finish it anyways.

**Comment by tacone** [comment]
Update: I reimplemented the nested-set tree building in memory, since Baum was making too much queries (100+ writes for just 10 elements). Now the maximum writes should be 1 changed for element (thus a maximum of 10 writes over a 10 elements tree).

I still have a bug on siblings order and lack any kind of language localization.

I very much hope to be able to finish tomorrow.

**Comment by tacone** [comment]
Here it is:
https://github.com/zofe/rapyd-laravel/pull/256

**Comment by tacone** [comment]
We should add a notice somewhere in the README to inform the user that the need to install baum in order to use the DataTree, After that, it's all done.
