### ISSUE TITLE
Sensible "empty" behaviour for DataSet and derivatives.

### ISSUE THREAD

**Issue by JamesGuthrie** [zofe/rapyd-laravel#254]
I'm using a DataGrid which may be empty, I assume that this issue corresponds to the DataSet as well as the DataFilter. It seems as though rapyd basically ignores the fact that its empty, merely showing an unpopulated table. I thought I would wrap the datagrid view in my own view which conditionally shows the DataGrid or not, something like:
```
@if(count($grid->rows) == 0)
    There is nothing to see here
@else
    @include('rapyd.grid')
@endif
```
The problem is that at that point there is no way to query the grid to determine how many rows will be shown because it has not been built yet. I could run the query which is being passed to Rapyd, but in the DataFilter case this will break (I don't know by what Rapyd is filtering), and it results in the same query being executed twice.

I then tried building the grid first:
```php
$grid->build()
return view('my.view', compact('grid'));
```

This doesn't work as the grid shows the results twice.

While I get that it's possible to customise the rendering of the grid view, this seems like such a basic case that it ought to be supported in Rapyd itself. Can Rapyd have some sensible behaviour when empty?

**Comment by tacone** [comment]
Interesting. First of all, if you feel like submitting a patch for the grid view, I guess it would be welcome.

Secondly, Datagrid should perhaps check `$this->output` to see if it needs building or it's already built.

As a temporary workaround, you may do this:

```
$gridOutput = (string) $grid;
return view('my.view', compact('grid', 'gridOutput'));
```

```
@if(count($grid->rows) == 0)
    There is nothing to see here
@else
    {!! $gridOutput !!}
@endif
```

**Comment by JamesGuthrie** [comment]
I've opened #255 which adds this behaviour to the DataGrid.

**Comment by tacone** [comment]
Looks good. I've pinged @zofe about it.

Thank you for now.

**Comment by zofe** [comment]
merged, thanks @JamesGuthrie
