### ISSUE TITLE
Disable demo

### ISSUE THREAD

**Issue by skydiver** [zofe/rapyd-laravel#261]
How do you disable the demo routes?

**Comment by zofe** [comment]
comment out this line
```php
#  /app/Http/rapyd.php
// Route::controller('rapyd-demo','\Zofe\Rapyd\Demo\DemoController');
```

**Comment by skydiver** [comment]
Commenting the line on `/app/Http/rapyd.php` doesn't disable.

The demo is still loaded from `vendor/zofe/rapyd/src/routes.php`, but don't want to modify the package source.

**Comment by tacone** [comment]
@skydriver, it should as long as you don't delete `/app/Http/rapyd.php`.

On another note, I guess that line should be commented by default also in `vendor/zofe/rapyd/src/routes.php`, perhaps with a comment right above stating "enable this to enable rapyd demo".
