### ISSUE TITLE
Laravel 5.2

### ISSUE THREAD

**Issue by kellyburton** [zofe/rapyd-laravel#263]
2.1.* does not work with Laravel 5.2 release.  I tried the updated and it failed due a missing dependency with Rapyd.  

I rolled back to 5.1.

**Comment by tacone** [comment]
You should provide more details.

**Comment by lukas1008k** [comment]
In laravel 5.2 is problem with this:
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Fatal error: Call to undefined method Illuminate\Foundation\Application::bindShared()

**Comment by tacone** [comment]
Thank you to all.
A new branch has been opened to try to make it work on Laravel 5.2: https://github.com/zofe/rapyd-laravel/tree/2.2
Feel free to contribute :)

**Comment by zofe** [comment]
I think I've fixed,   please use:
"zofe/rapyd": "2.2.*"

there are a lot of changes, but demo runs  fine

**Comment by kellyburton** [comment]
I apologize for leaving a short note just saying it doesn't work. As a developer I know these kind of tickets are frustrating for the author of the software as they have no idea what the user's problem is. I was in a hurry due to the holiday and just wanted to let you know there was a problem with 5.2.   Thank you to all the others who posted and clarified the situation for me, and to Zofe for patching so quickly.
