### ISSUE TITLE
Class 'Illuminate\Html\FormFacade' not found

### ISSUE THREAD

**Issue by andreev1024** [zofe/rapyd-laravel#265]
Hello.In composer.json I have:
```
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "laravelcollective/html": "5.2.*",
        "zofe/rapyd": "2.2.*"
    },
```
After `composer update` I've got http://joxi.ru/BA0pbNWfBPYz8A

`vendor/zofe/rapyd/src/macro.php` use `Illuminate\Html\FormFacade`, but laravelcollective FormFacade has other namespace (`Collective\Html\FormFacade`). Am I wrong?

**Comment by tacone** [comment]
Could you try to fix, test and send a pull?

**Comment by andreev1024** [comment]
I'll replace all `Illuminate\Html*` to `Collective\Html*`. If it's ok then I can do this.

**Comment by tacone** [comment]
if it works feel free to submit the PR, and thank you for you help.
