### ISSUE TITLE
How to Show Serial number on DataGrid

### ISSUE THREAD

**Issue by sayemk** [zofe/rapyd-laravel#272]
I want to show a serial number not the ID field of table in DataGrid View. Is it possible

**Comment by zofe** [comment]
incomprehensible

**Comment by sayemk** [comment]
Uh, I want show a row serial number like 1,2,3,4.....

**Comment by zofe** [comment]
understood 
there is nothing predefined.. you can do something like:
```php
$grid->add('id','ID')->cell( function( $value, $row) {
    static $id = 0;
    return ++$id;
});
But if you need to show the "sequential number" at page x   you should calculate the offset (maybe using \Input::get('page') * items per page + $id
```

**Comment by sayemk** [comment]
Thanks, It is working

**Comment by arivu1995** [comment]
Its working but i need to set numbers for all records in the grid like 1 to n numbers continuously.. 
Thanks in Advance.
