### ISSUE TITLE
Laravel 5.2 CheckBox Problem

### ISSUE THREAD

**Issue by beqwulf** [zofe/rapyd-laravel#277]
Hello;
in DataEdit Form create a checkbox return a error

FatalErrorException in FormBuilder.php line 1110:
Call to a member function toArray() on a non-object

Please help

**Comment by tacone** [comment]
Please post your code.

**Comment by beqwulf** [comment]
In UserController.php

    public function create()
    {
        $edit = \DataEdit::source(new User);
        
        $edit->label('User Edit');
        $edit->link("/users","Back", "TR")->back();
        
        $edit->add('tax_administration','Tax Admin.', 'text')->rule('required|min:5');
        $edit->add('tax_number','Tax Number', 'text')->rule('required|min:5');
        $edit->add('locked', 'Locked', 'checkbox'); // This line create a error
        
        return $edit->view('users.create', compact('edit'));
    }
    
if i add this line  $edit->add('locked', 'Locked', 'checkbox'); return a error message.

And i debug the code vendor/zofe/rapyd/src/dataform/Field/checkbox.php

$output = Form::checkbox($this->name, $this->checked_value, $this->checked, $this->attributes) . $this->extra_output; 

if i comment this line, code run but checkbox not seem.

**Comment by beqwulf** [comment]
i find solution my self :D. Problem is in laravelcollection.
if you dont define Attribute function for field in model, you will get this error message.

i define a function in USER model problem is gone...
   public function LockedAttribute($value)
    {
        return null;
    }

**Comment by tacone** [comment]
Nice to see you solved. Could you close this issue then?
