### ISSUE TITLE
DataForm, redactor filed fail to upload Image

### ISSUE THREAD

**Issue by sayemk** [zofe/rapyd-laravel#288]
**redactor**  for **wysiwyg** box it is failed to upload image; Errors is **CSRF token Mismatch **

You can view in demo site also

**Comment by zofe** [comment]
you can add an exception on your Http/Middleware/verifyCsrfToken.php file using the uri of your upload  script.
I must close this because is not related to rapyd, and redactor  is  currently  included but no longer supported.
