### ISSUE TITLE
addText in DataForm doesnt work

### ISSUE THREAD

**Issue by elendil1979** [zofe/rapyd-laravel#291]
The methods of adding fields in the DataForm class does not work correctly. They are invoked through the _call method of the class and this is a mistake.

I show you a error screen example:

FatalErrorException in DataForm.php line 119:
Class '\Zofe\Rapyd\DataForm\Field\Required' not found

and my code:

  /**
   * @param DataForm $form
   * @return DataForm
   */
  public function setFormFields($form) {
   // This call fail because DataForm try instance class Required like a form field type
    $form->text('menu','Menu','required');  
    $form->text('icono','Icono','required');
    $form->number('orden','Orden','required|integer|min:0');
    return $form;
  }

The reason for the failure is because in the add signature method, rules as the fourth parameter, the input type as a third party, and the method of _call DataForm class ignore that order when invoke the add method. This is the add method signature

/**
     * @param string $name
     * @param string $label
     * @param string $type
     * @param string $validation
     *
     * @return mixed
     */
    public function add($name, $label, $type, $validation = '')

**Comment by zofe** [comment]
wrong usage of validation rules

**Comment by tacone** [comment]
Also see http://www.rapyd.com/rapyd-demo/form for the right syntax.

**Comment by elendil1979** [comment]
In the doc of DataForm class you can read that method text is a shortcout to add with this signature
* @method Text         text        (string $name, string $label, $validation = '')

this way you can use $validation with third params

I used $form->text($name,$label)->rules($rules)  and work but if i try use
$form->text($name,$label,$rules) apply the signatura write in docs, it is fail. Or doc is wrong or the code is wrong i think

**Comment by tacone** [comment]
that doc is wrong, thank you for noticing. we'll take care of that.
