### ISSUE TITLE
DataEdit custom HTML for show context

### ISSUE THREAD

**Issue by gradosevic** [zofe/rapyd-laravel#297]
Is there a way to wrap up form fields in DataEdit with custom HTML (or Blade) like we can do in DataGrid? 

I have something like this:
```
$edit = DataEdit::source(new User);
$edit->add('status', 'Status', 'text');
```

I would like to do something like this:
```
$status = Status::find($edit->model->status_id);
$edit->add('<a href="statuses/edit?show='.$status->id.'"  >'.$status->name.'</a>', 'Status', 'html');
```
This will work only when showing record (does not make sense for editing mode), this link could point to status record from different table and it would be much easier to find that related record.

Thanks for such great library!

**Comment by zofe** [comment]
https://github.com/zofe/rapyd-laravel/wiki/Field-list
"container" field

**Comment by gradosevic** [comment]
It worked as expected. Thanks!
