### ISSUE TITLE
->rule('unique .... Is it possible?

### ISSUE THREAD

**Issue by pastebimas** [zofe/rapyd-laravel#299]
Hey, 
I need to make, that it wont be possible to create new entry if it's name are already used. How can I pass such thing to CRUD edit?

$this->edit->add('login','Login name','text')->rule('unique:login');

Then it seems ok untill I press SAVE. And I get error:
`Base table or view not found: 1146 Table 'database_projektas.login' doesn't exist (SQL: select count(*) as aggregate from `login` where `login` = test)`

That table is called "commission", so if I try:
$this->edit->add('login','Login name','text')->rule('unique:commission.login');

I get:
Database [commission] not configured.

Am I missing something? Thank you

**Comment by tacone** [comment]
I think you should review Laravel's docs for the right syntax :) I'd bet on something like `$this->edit->add('login','Login name','text')->rule('unique:commission');` though

**Comment by zofe** [comment]
should be `unique:Table,Field` with a comma

**Comment by pastebimas** [comment]
Thank you, It does work :)
