### ISSUE TITLE
Have not been deleted

### ISSUE THREAD

**Issue by mostwin** [zofe/rapyd-laravel#308]
hi:
When I click the url
http://www.rapyd.com/rapyd-demo/edit?delete=20

table: demo_article_category
not been deleted (related data)

**Comment by tacone** [comment]
you need to click the confirmation button displayed in the resulting page.

**Comment by mostwin** [comment]
I mean, it is not delete related data  table demo_article_category

**Comment by zofe** [comment]
@mostwin proper replication, but the problem is not related to rapyd itself.  
We need some constraint ( ->onDelete('cascade'))  on the demo.  Thanks for the tip.
