### ISSUE TITLE
How to delete dependable record from another table on do_delete action?

### ISSUE THREAD

**Issue by gradosevic** [zofe/rapyd-laravel#319]
I have two tables "users" and "licenses". Users table has foreign key to licenses table id. When I want to delete users table record I use something like this in my edit method:

```
$delete_id= Request::input('do_delete');
$user = new User;
if($delete_id){
 $user = User::find($delete_id);
 $license = License::find($user->license_id);
 $license->delete();
}
```
I get "_SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails_" error.

This probably happens because I'm trying to delete license record before user record is deleted. How can I run my custom code after user record is deleted?

**Comment by zofe** [comment]
You can take care about integrity or cleanup orphan files  using  events in your models.
i.e.:
https://github.com/zofe/rapyd-laravel/blob/master/src/Demo/Article.php#L42
I prefer this approach over constraint

**Comment by tacone** [comment]
Smells fishy.
You should update your migrations to do something on delete.

**Comment by gradosevic** [comment]
@tacone I agree with you, this should be preferred way, but in my particular case I don't have user foreign key in licenses table.

@zofe Thanks! This is my solution on User model:

```
protected static function boot()
    {
        parent::boot();
        static::deleted(function ($user) {
            $license = License::find($user->license_id);
            if($license){
                 $license->delete();
            };
        });
    }
```
