### ISSUE TITLE
Help need to implement the DataTree

### ISSUE THREAD

**Issue by aabir** [zofe/rapyd-laravel#320]
@tacone
I tried to run Data tree in localhost (http://localhost/rapyd2/public/rapyd-demo/datatree) like show in http://www.rapyd.com/rapyd-demo/datatree here and I have installed https://github.com/etrepat/baum but getting a blank page with Documenter only. No error even, no clue to what to do. Help appreciated.
Thanks.

**Comment by tacone** [comment]
Did you remember to publish the assets?

Secondly, if you installed Baum after Rapyd, you may want to run again the migration, by using the DemoController::getSchema (should be the localhost equivalent of http://www.rapyd.com/rapyd-demo/schema).

Hope this helps :)

**Comment by aabir** [comment]
Yes, I did vendor publish. 
And also re-populate the database from schema as well as run the migration, demo_menus table is already there, no luck, still the blank page with documenter. 
Thanks.

**Comment by zofe** [comment]
check your source to see if  scripts & css  are loaded from correct path,
if not, the problem  is related  to your vhost configuration & laravel: 
Basically  assets are loaded via an HTML helper https://laravelcollective.com/docs/5.2/html#generating-urls

**Comment by aabir** [comment]
Yes I checked, all the css and scripts are loading correctly. Here is the loaded scripts - 
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.pjax/1.9.6/jquery.pjax.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/riot/2.2.4/riot+compiler.min.js"></script>

<script src="http://localhost/rapyd2/public/packages/zofe/rapyd/assets/datatree/js/nestable/jquery.nestable.js"></script>
<script src="http://localhost/rapyd2/public/packages/zofe/rapyd/assets/datatree/js/datatree.js"></script>
   
Thanks.

**Comment by tacone** [comment]
You should insepect your javascript console, the apache error log, and storage/logs/laravel.log for errors.

Also you may try to edit the DemoController to put a `dd` or `var_dump` to see if the data is properly loaded from the db.

**Comment by aabir** [comment]
Sorry for late reply. 
I inspected the console and getting a error "Uncaught SyntaxError: Failed to execute 'querySelectorAll' on 'Document': The provided selector is empty." from riot+compiler.js. 

My laravel.log file is error less. 

I also edit the DemoController, anyDatatree method and put var_dump on $root. Here is the result I got. https://gist.github.com/aabir/334e81dfee8638364671b9069f927bf8

I guess Baum (https://github.com/etrepat/baum) is not compatible with Laravel 5.2, not sure though. 

Thanks.

**Comment by zofe** [comment]
@aabir  about riot  it's the same on the online (which runs on 5.1), not seems it's not related to baum.
But I can confirm that on a fresh installation of  the 5.2  I've the same problem  no output.

**Comment by tacone** [comment]
@aabir @zofe I hope to be able to take a look into it in the weekend. Will let you know.

**Comment by tacone** [comment]
It turns out Rapyd internal API changes broke the DataTree more or less one month ago. Thank you for alerting us @aabir, we fixed the issue.

**Comment by aabir** [comment]
Thank you @tacone.
