### ISSUE TITLE
Autocomplete and tags not working properly in Laravel 5.2

### ISSUE THREAD

**Issue by jmdolson** [zofe/rapyd-laravel#323]
The route for AJAX calls to get autocomplete/tags information 

> Route::get('rapyd-ajax/{hash}', array('as' => 'rapyd.remote', 'uses' => '\Zofe\Rapyd\Controllers\AjaxController@getRemote'));

is not loaded with web middleware and therefore does not receive session data on which it depends. After publishing rapyd.php with artisan vendor:publish I added web middleware

> Route::get('rapyd-ajax/{hash}', array('middleware'=> 'web', 'as' => 'rapyd.remote', 'uses' => '\Zofe\Rapyd\Controllers\AjaxController@getRemote'));

Since it can be published and changed, its a pretty easy fix, but I thought I'd share.

**Comment by zofe** [comment]
thanks @jmdolson ,  any suggestion about how to keep same code for  5.1/5.2  ? (master branch is a 99% compatible  with both)

**Comment by azrael-sub7** [comment]
I don't think is possible without a check. 
I notice only 5.2 has the method 'hasMiddleware' so this should work:


    if( method_exists( 'App\Http\Kernel' ,'hasMiddleware' )){
    Route::get('rapyd-ajax/{hash}', array('middleware'=> 'web', 'as' => 'rapyd.remote', 'uses' => '\Zofe\Rapyd\Controllers\AjaxController@getRemote'));
    }else{
    Route::get('rapyd-ajax/{hash}', array('as' => 'rapyd.remote', 'uses' =>   '\Zofe\Rapyd\Controllers\AjaxController@getRemote')); 
    }

**Comment by mberende** [comment]
I have tried this fix on Laravel 5.2 and it does not work

**Comment by zofe** [comment]
@mberende 
i can confirm that  adding web middleware  works on a 5.2
```php
Route::get('rapyd-ajax/{hash}', [
'middleware'=> 'web', 
'as' => 'rapyd.remote',
'uses' => '\Zofe\Rapyd\Controllers\AjaxController@getRemote']);
```

**Comment by mberende** [comment]
This is an issue caused by Laravel 5.2 If you somehow add the web middleware twice (once in routing and once in controller) your session will not work. I removed all manual addings of middleware from controllers and edited config/rapyd.php just like bellow  and the issue got fixed.

Route::group(['middleware' => 'web'], function () {

    Route::get('rapyd-ajax/{hash}', ['as' => 'rapyd.remote', 'uses' => '\Zofe\Rapyd\Controllers\AjaxController@getRemote']);
    Route::controller('rapyd-demo', 'Zofe\Rapyd\Demo\DemoController');

});
