### ISSUE TITLE
Get element of radiogroup and select

### ISSUE THREAD

**Issue by kenk11** [zofe/rapyd-laravel#324]
In my class ProductController
` $this->edit->add('brand', 'Brand', 'radiogroup')->options(\App\Brand::lists('brand_name')->all());`
It works for display but after submit, it just gets index not value,

How to get value from select or radiogroup?

**Comment by kenk11** [comment]
Anyone can help me get value from `select` or `radiogroup`?
Its only get index

**Comment by tacone** [comment]
Quite frankly, it's very unclear what you are asking. Try pasting here the output you get and an example of the output you'd like.

**Comment by kenk11** [comment]
here is my DataEdit
![screenshot 8](https://cloud.githubusercontent.com/assets/11768306/15143259/fec8b58e-16d2-11e6-97e7-41def2a13d17.png)

and my DataGrid
![screenshot 9](https://cloud.githubusercontent.com/assets/11768306/15143277/0d8ccc36-16d3-11e6-94e1-c6913f1cf2ed.png)

ProductController
`
    public function edit($entity)
    {
        parent::edit($entity);
        $this->edit = \DataEdit::source(new \App\Product());
        $this->edit->label('Add/Edit Product');


        $this->edit->add('product_id', 'Product ID', 'text')->rule('required');
        $this->edit->add('product_name', 'Product Name', 'text');
        $this->edit->add('product_spec', 'Specification', 'redactor');
        $this->edit->add('product_price', 'Price', 'number');
        $this->edit->add('brand_name', 'Brand', 'select')->options(\App\Brand::lists('brand_name')->all());
        $this->edit->add('product_img', 'Image', 'image')->move('images/product/')->preview(160, 160);
        $this->edit->saved(function () use ($entity) {
            $this->edit->message('Awesome, Data Saved successfully');
            $this->edit->link('panel/Product/all', 'Back');
        });
        return $this->returnEditView();
    }

`
I tried with many way but still cant get brand_name

**Comment by tacone** [comment]
You should ensure the product model contains a working relation to the brand and then change your datagrid (not your dataedit) to invoke it useing the dot notation like this:

```
$grid->add('brand.brand_name', 'Brand');
```

Hope it will help.

**Comment by kenk11** [comment]
OMG, it worked :+1: 
i remember i tried that way
thanks anyway!
