### ISSUE TITLE
unique validation working wrong on update

### ISSUE THREAD

**Issue by drickferreira** [zofe/rapyd-laravel#333]
My code:

public function edit() {
$form = \DataEdit::source(new User);
$form->link("user","Usuários", "TR")->back();
$form->text('username','Usuário')->rule('required|max:20|unique:users');
$form->text('name','Nome')->rule('required|max:255');
$form->text('email','Email')->rule('required|email|max:255|unique:users');
$form->build();
return $form->view('user.edit', compact('form'));
}

The rules works fine on insert, but the unique rule is activating on update:
**username already used.
email already used.**

Did not have to ignore the current record on update?

**Comment by zofe** [comment]
I'll check this..
Thanks for the detailed issue tracking,
but please (to all interested)  sometimes It's a good idea to help in the development i.e.: find a solution, submit a P.R., etc..

**Comment by zofe** [comment]
By default the laravel validation is always executed on a rapyd form (dataform & dataedit).
So on a dataedit  is executed on insert and update..  
I remember a custom method in the code:
https://github.com/zofe/rapyd-laravel/blob/master/src/DataForm/Field/Field.php#L182
can you try to switch to this  and check if is  it work as expected

**Comment by drickferreira** [comment]
This works great!

I used this:
$form->text('username','Usuário')->rule('required|max:20')->unique();

And I tested this, to allow equals 'cpf_cpnj' on different companies, and this works too.

$form->text('cpf_cnpj','CPF / CNPJ')->rule('required|min:14')->unique(null, null ,'company_id,'.Auth::user()->company_id);

Thanks a lot.

**Comment by zofe** [comment]
@drickferreira You're welcome.
