### ISSUE TITLE
Edit button not functional in DataGrid

### ISSUE THREAD

**Issue by mathewsee** [zofe/rapyd-laravel#335]
Hi guys I face some issue in the DataGrid issue, please refer to my code below
`$filter = \DataFilter::source(new company);
        $filter->add('COMP_NAME','COMPANY NAME', 'text');
        $filter->submit('search');
        $filter->reset('reset');

        //Listing data table
        $grid = \DataGrid::source($filter);  //same source types of DataSet
        $grid->add('COMP_NAME','COMPANY NAME', true); //field name, label, sortable
        $grid->add('COMP_REG','REGISTRATION.NO', true);
        $grid->add('COMP_UNIT','TOTAL SHARE'); 
        $grid->edit('/eCompany', 'Action','modify|delete'); //shortcut to link DataEdit actions`
In my company table, my PK would be COMP_ID which stands for my ID which causing ` $grid->edit('/eCompany', 'Action','modify|delete');` unable to grab the ID and place into the link.

Is there anyway to work around?

**Comment by zofe** [comment]
you need to specify your PK in your Company model

    public $primaryKey = 'COMP_ID';

this is a "eloquent" stuff is not related with rapyd.

**Comment by mathewsee** [comment]
IT WORKS! THANKS! Like magic!
