### ISSUE TITLE
Binary File display as Image in Datatable

### ISSUE THREAD

**Issue by mathewsee** [zofe/rapyd-laravel#336]
Hi there, as the title mention we have store our image as binary file in database [long blob]. Is it possible to display it as image in DataGrid?

**Comment by tacone** [comment]
You may use the blade syntax:

```
$grid->add('{{ myfunc($blobfield) }}', 'My Image');
```
The above sample assumes your blob field is named `blobfield` in the database, and that you have a PHP function somewhere that prints an image tag with the proper base64 dataurl.

**Comment by mathewsee** [comment]
I quite new to this framework so I can't understand how it works actually. Please refer to my code below as reference

`//Listing data table
        $grid = \DataGrid::source($filter);  //same source types of DataSet
        $grid->add('COMP_IMG', 'Logo'); //blob data
        $grid->add('COMP_NAME','COMPANY NAME', true); //field name, label, sortable
        $grid->add('COMP_REG','REGISTRATION.NO', true);
        $grid->add('COMP_UNIT','TOTAL SHARE'); 
        $grid->edit('/eCompany', 'Action','modify|delete'); //shortcut to link DataEdit actions
        $grid->link('/eCompany',"Add New Company", "TR");  //add button
        $grid->orderBy('COMP_NAME','ASC'); //default orderby
        $grid->paginate(10); //pagination`

this is my code and currently how i display my data is by use this following method in a form format
`<img id = "COMP_IMG" name = "COMP_IMG" src="data:image;base64,{{$data->COMP_IMG}}"  border="5" width="150px" height="150px"/>`

so if i want to display a blob image at datagrid what should I do in my function?

**Comment by tacone** [comment]
I suggest you to try this:

```php
        $grid->add('<img src="data:image;base64,{{ $COMP_IMG }}" border="5" width="150px" height="150px"/>', 'Logo'); //blob data
     
```

**Comment by mathewsee** [comment]
WOW it works perfectly! THanks!
