### ISSUE TITLE
DataFilter and DataGrid error in joining two tables

### ISSUE THREAD

**Issue by cheeleong1993** [zofe/rapyd-laravel#337]
Guys!

I have a problem. I tried to join two tables so that both data in the tables can be display together with the DataGrid function. But i doesn't work.

My controller:

        $dataJoin = DB::table('shareholder')
                    ->join('shareholder_extended', 'shareholder.SHARE_ID', '=',                                                                                       'shareholder_extended.SHAREX_SHARE_ID')
                     ->where('shareholder.SHARE_STATUS', '!=', 8)
                     ->orWhere('shareholder_extended.SHAREX_STATUS', '!=', 8)
                     ->get();

        $filter = \DataFilter::source($dataJoin);

        $filter->text('src','Search')->scope('freesearch');
        $filter->submit('search');
        $filter->reset('reset');
        $filter->build();
    
        $grid = \DataGrid::source($filter);
        $grid->add('SHAREX_NAME','PROXY NAME'); 
        $grid->add('SHAREX_IC','PROXY IC');

My model:

```php
class shareholder_extended extends Model
{
    protected $table = "shareholder_extended";
    public $primaryKey = 'SHAREX_ID';

    public function scopeFreesearch($query, $value)
    {
        return $query->where('SHAREX_NAME','like','%'.$value.'%')
            ->orWhere('SHAREX_SESSIONID','like','%'.$value.'%');

    }
}
```

It returned me the error:

FatalErrorException in f97245b6f50733de8874701e9c88da84fd2d57b0.php line 0:
Method Zofe\Rapyd\DataGrid\DataGrid::__toString() must not throw an exception, caught Error: Call to a member function count() on array

Anyway to solve this ? Thank you.

**Comment by tacone** [comment]
Try without `->get();`

**Comment by cheeleong1993** [comment]
hi @tacone , i had tried remove the ->get(); , it seems worked but the datafilter for searching function is not working, it there related to the joining of the table?

**Comment by tacone** [comment]
Quite frankly I don't know. I suggest making sure that that scope works as intentended without rapyd.

**Comment by zofe** [comment]
```php
$query = DB::table('shareholder')
                ->join('shareholder_extended', 'shareholder.SHARE_ID', '=',                                                                                       'shareholder_extended.SHAREX_SHARE_ID')
                 ->where('shareholder.SHARE_STATUS', '!=', 8)
                 ->orWhere('shareholder_extended.SHAREX_STATUS', '!=', 8);

$filter = \DataFilter::source($query);
$filter->add('ricerca', 'nome vetrina, regione, provincia', 'text')->scope(function ($query, $search) {
            return $query->where('SHAREX_NAME','like','%'.$value.'%')
        ->orWhere('SHAREX_SESSIONID','like','%'.$value.'%');
        })
...
```
if you don't start from a "model"  (so an Eloquent\Builder)  datafilter can't reach the query scope.
So you must simply use a closure   as above.

**Comment by cheeleong1993** [comment]
hi, i realized that i should use model but not join the table. Anyway, thanks all.

controller:

$res = shareholder_extended::with('shareholder')
                                    -> has('shareholder', '>=', '1')
                                    -> where ('shareholder_extended.SHAREX_STATUS', '!=', 8);
$filter = \DataFilter::source($res);
