### ISSUE TITLE
Redactor Not Display in view

### ISSUE THREAD

**Issue by CHOMNANP** [zofe/rapyd-laravel#339]
Hi,

When I download Rapyd, the Redactor working find with the Demo.

But when I try this in my view.
$form->add('description','Description', 'redactor');

The field description display like a normal text area.
When I try replace "@extends('layouts.app') " with "@extends('rapyd::demo.master')" in my form, then the redactor work. 

Could you let me know is there anything I need to include in my 'layouts.app'?

Thanks,
Punleu

**Comment by tacone** [comment]
You need to print `Rapyd::styles()` and `Rapyd::scripts()` somewhere in your layout. Also make sure you have published the package assets.

**Comment by CHOMNANP** [comment]
Hi Tacone,

I am new to Laravel.
I have published Rapyd already. That's why I can see the demo in my app using route "".

Already include "{!! Rapyd::styles() !!}" and "{!! Rapyd::scripts(true) !!}" in my layout "app.blade.php".

The redactor still not working :(
Any idea?

Thanks,
Punleu

**Comment by zofe** [comment]
just compare your layout  with  the demo master:
https://github.com/zofe/rapyd-laravel/blob/master/views/demo/master.blade.php#L68
please note that scripts must be loaded "after" jquery inclusion.

**Comment by CHOMNANP** [comment]
Hi Zofe,

Thank you it works now.
Actually, it's the order of putting "{!! Rapyd::scripts() !!}". It work unless I put "{!! Rapyd::scripts() !!}" as the last script to run ( put "{!! Rapyd::scripts() !!}" most bottom near </body>);

Thank you :)
Punleu
