### ISSUE TITLE
Can't save data

### ISSUE THREAD

**Issue by coderlazy** [zofe/rapyd-laravel#341]
This is my form:
```php
        $skillTags = (new \App\Skilltag())->getAllTagName();
        $emailMeJob = new \App\EmailMeJobs();
        $form = \DataForm::source($emailMeJob);
        $form->add('email', 'Email Address', 'text', 'Enter your email address', false, '')
                ->rule('required');
        $form->add('job', 'Every Week Send Me', 'text')
                ->attributes(['placeholder' => 'Job title or description. eg PHP developer']);
        $form->add('skill_id', 'Jobs In (Category)', 'select')
                ->rule('required')
                ->attributes(['name' => 'skill_id[]', 'placeholder' => 'Select category', "multiple" => "multiple"]);
        $form->add('job_level', 'Job Level*', 'select')
                ->rule('required')
                ->options(trans('form.job_level'))
                ->attributes(['placeholder' => 'All job level']);
        $form->add('positions', 'That Are Located In', 'select')
                ->options(['Tất cả'])
                ->attributes(['name' => 'positions[]', "multiple" => "multiple"]);
        $form->add('expected_salary', 'With Salary Of', 'number')
                ->attributes(['placeholder' => 'Minimum monthly salary (USD)']);
        $form->submit('Email me job');
        $province = \App\Province::getLocation(USER_LOCALE);
        $form->saved(function () use ($form) {
            
        });
        $form->build();
        return $form->view('common.jobalert', compact('form', 'skillTags', 'province'));
````

**when click to submit button data not save to table and this is bug:**
`SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'email' cannot be null (SQL: insert into `email_job_to_guest` (`email`, `job`, `skill_id`, `job_level`, `positions`, `expected_salary`, `updated_at`, `created_at`) values (, , , , , , 2016-07-16 15:16:43, 2016-07-16 15:16:43)).
`
Help me pls!

**Comment by zofe** [comment]
you must know a bit laravel routing.. probably you roted only the "get" method,  
you should use "any"  instead  (to catch both get and post).

https://github.com/zofe/rapyd-laravel/wiki/DataEdit#routing-only-a-dataedit

**Comment by coderlazy** [comment]
+ This is my model:
`<?php
namespace App;
use Illuminate\Database\Eloquent\Model;
class EmailMeJobs extends Model {
    protected $guarded = ['id'];
    protected $table = 'email_job_to_guest';
}`
+ my routes:
Route::any('job-alert', 'FrontendController@anyJobalert');
+ data when i dd() post request:
array:8 [▼
  "_token" => "nBw9hn5Vi6ZMPwP2ZXlrig5qx6Xvsktks1nhmrl0"
  "job" => ""
  "skill_id" => array:1 [▶]
  "job_level" => "2"
  "positions" => array:1 [▶]
  "expected_salary" => "1000"
  "email" => "dev@yopmail.com"
  "process" => "1"
]
thanks

**Comment by zofe** [comment]
it seems that \Input::get() (internally used by rapyd)  is not working for you.. 
in some recent versions or  laravel the \Input facade was removed,  but  Rapyd just take care of this  adding the the input facade on the fly..  
https://github.com/zofe/rapyd-laravel/blob/master/src/RapydServiceProvider.php#L62

So, what's the version you're using  (both laravel and rapyd one)?
