### ISSUE TITLE
How to exclude the current id from parents?

### ISSUE THREAD

**Issue by heimasi** [zofe/rapyd-laravel#345]
In DataEdit, 

$edit->add('parent_id', 'Parent', 'select')->option('0','Top Category')->options(Coursecategory::lists('category_name','id'));

When creating a record, it works!
When editing a record, self id is showed in Parent select element. How to exclude the current id from Parent select? Thanks!

**Comment by zofe** [comment]
can be easy  to detect  current action/status  form current qs or url method of the widget:
```php
if ($edit->url->value('modify|update') {
   //will be executed only on modify status and update action
} else {
   //will be executed in any other case  (show, create, insert, etc..)
}

**Comment by heimasi** [comment]
Thanks for your reply. Actually, I don't know how to access the current editing model in editing status?

**Comment by heimasi** [comment]
oh, sorry, I'm so stupid, I get it. I close this issue!
