### ISSUE TITLE
Users with same roles.

### ISSUE THREAD

**Issue by raylight75** [zofe/rapyd-laravel#346]
I have question about how to manage resources with users with same roles.
If i have 2 users from same roles editors for example, they can view resources when we change query string in Url.
I  made midlleware but this work good only for show and modify string.
```php
public function handle(Request $request, Closure $next)
    {
        $user = User::findOrFail($request->all())->first();
        if ($user->id === Auth::user()->id) {
            return $next($request);
        }
        return redirect('backend/profile')->withErrors('Your are not autorized to view resources');
    }
```
When i press save button Laravel show me 404 not found
I have doubt that update method use Patch and my request can handle it.
If i remove midlleware everythink working fine.

**Comment by raylight75** [comment]
Well i solve the problem but i think when we have users with same role the only place at the moment where we can get parameter is Url. From the security reason have much more sense parameters to pass inside controller, well i found in request parameter save(maybe for button) that break request.
I make if else statement but for me this is not the right way to deal with this.
```php
public function handle(Request $request, Closure $next)
    {
        if ($request->has('update')) {
            $user = User::where('id', $request->input('update'))->first();
        } else {
            $user = User::findOrFail($request->all())->first();
        }
        if ($user->id === $this->auth->user()->id) {
            return $next($request);
        }
        return redirect('backend/profile')->withErrors('Your are not autorized to view resources');
    }
```

**Comment by zofe** [comment]
This is related to laravel,  I mean security in general is not granted by "hidden fields" and POST method.
I understand that  using GET parameters make feel you more exposed but an ACL should be always present in a CRUD app, and it's not included in rapyd just because it's already provided by laravel.

Somethimes I work as is:
- I prefer using DataForm insetead DataEdit  because there are less interactions to take care
- Then I define some policy in the AuthServiceProvider, mostly managed by models
- On User model and in a trait I define the "owner" relation/concept and sometimes also a "role hierarchy"

```php

<?php

namespace App\Providers;

use Illuminate\Contracts\Auth\Access\Gate as GateContract;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;

class AuthServiceProvider extends ServiceProvider
{
    public function boot(GateContract $gate)
    {
        //
        $gate->define('is-owner', function($user, $item){
            return $user->owns($item);
        });

        $gate->define('manage-if-admin', function($user){
            return $user->super_admin > 0;
        });
    }
}

```

```php

```

```php

public function anyEdit($id)
    {
        $model = Blog::findOrNew($id);
        if ($model) 
        {
           if (Gate::denies('is-owner', $model)) 
           {
               abort(403, 'Your are not autorized...');
           }
        }
        
        $form = \DataForm::source($model);
        ....
        $form->set('user_id', \Auth::user()->id, true, false);

```

```php
class User extends \Eloquent
...
    public function owns($related) 
    {
        if ($this->super_admin > 0)
        {
            return true;
        }
        return ($this->id == $related->user_id);
    }
```

**Comment by raylight75** [comment]
Yes  i know and agree with you, i have same policy in AuthServiceProvider but we need parameter(id) in this case from Url, and this is related to rapyd because i made investigation why update not working.
Maybe you need to specify in Help if you pass additional fields in request(in that case save button).
