### ISSUE TITLE
How to Redirect after successful DataEdit Form submit

### ISSUE THREAD

**Issue by maximusblade** [zofe/rapyd-laravel#347]
This may have been covered before.
I never got a definitive solution.
Either I dont understand the documentation or im doing something wrong.

This code does not redirect to the intended destination.
it just refreshed back to the form.
I need some help.

    public function create()
    {
        $this->middleware('auth');
        $this->user = Auth::user();

        $edit = \DataEdit::source(new Events());
        $edit->link('/castings/user', 'My Castings / Events', 'TR')->back();
        $edit->add('user_id', '1', 'hidden')->insertValue(Auth::id());
        $edit->add('header', 'Title', 'text')->rule('required');

        $edit->add('description', 'Description', 'textarea')->rule('required');
        $edit->add('startdate', 'Start Date', 'date')->attributes(['placeholder' => 'Day/Month/Year', 'class' => 'datepicker'])->rule('required');
        $edit->submit('Edit User Details');

        $edit->saved(function () use ($edit) {
          Alert::success('Event Saved');

          return Redirect::route('castings.user');
        });

        $edit->build();

        return view('mb2016.casting.casting_edit', compact('edit'));
    }

**Comment by raylight75** [comment]
You use closure with Redirect, move 
```php
Redirect::route('castings.user');
````
 to the last line, and last line, if you prefer view this must be 
```php
return $edit->view
```

**Comment by maximusblade** [comment]
I want to redirect ONLY when saved.
and view when viewing.

**Comment by zofe** [comment]
follow what @raylight75 suggested, which is also documented here:
https://github.com/zofe/rapyd-laravel/wiki/DataEdit#view-render
