### ISSUE TITLE
Add layer of data manipulation on submit

### ISSUE THREAD

**Issue by pabloalbrecht** [zofe/rapyd-laravel#349]
Hi,

I've been through all the docs and the issues here but it seems I haven't found someone with a similar problem.

One of my table has a field 'user_id' which needs to be populated as the Auth::user()->id.

I add all the fields to my form using $form->add('username','Username','text')->rules(...) etc. but I'd like to be able to add an extra layer of data manipulation *before* the data is sent to the database by Rapyd.

The only option I can see without an extra data manipulation layer is to add a 'hidden' field with the user_id but for obvious reason I wouldn't do that.

Also I must say that I am fairly new to Laravel, I've finished a few of Laracasts series, and I apologize if this is solvable through Laravel directly.

**Edit**: also, I've tried already to add $form->saved(...) and $form->passed(...) but it doesn't work.
`$form->saved(function() use ($form){  dd($form); });` 

This never gets called

**Comment by zofe** [comment]
```php
$form->set('user_id', \Auth::user()->id, true, false);
```

set is intended to be used to fill data without  adding a field,  last two params are intended to  to be used to explain if the value should be used on insert, update,  or both.

**Comment by pabloalbrecht** [comment]
Thanks, $form->set did the trick.
