### ISSUE TITLE
Datagrid Filter Date

### ISSUE THREAD

**Issue by mathewsee** [zofe/rapyd-laravel#350]
Hi everyone, I facing an issue when I use the data filter. As the title mention it is related to the data.

As mention, my existing database date column is varchar(255) and it store the date as UNIX TIMESTAMP. Hence I face the problem is that how am I gonna select the or filter the data out and place it into the datagrid.

Any Idea in solve in this issue?

Thanks

**Comment by tacone** [comment]
There's no support for unix timestamps as far as I know. Rapyd only store dates in ISO format (yyyy-mm-dd).
