### ISSUE TITLE
DataGrid edit link

### ISSUE THREAD

**Issue by cheeleong1993** [zofe/rapyd-laravel#351]
![ask1](https://cloud.githubusercontent.com/assets/20177894/17387652/344118c6-5a28-11e6-9703-0d17f90b7c77.PNG)

Hi guys, i am facing a problem on the edit/delete in datagrid. The link i specified isn't work. In line 116, i am trying to edit the product and go to the url like:  http://localhost:8000/product/edit/1 . But when i click the  edit button, it give me different URL with error.

http://localhost:8000/product/edit/%7Bproduct%7D?modify=1

my route:
Route::get('/product/edit/{product}', 'adminController@editProduct')->middleware('admin', 'auth');
Route::patch('/product/{product}', 'adminController@updateProduct')->middleware('admin', 'auth');

Any way to solve this? Thanks.

**Comment by zofe** [comment]
hi @cheeleong1993 

- for next time, do not use printscreen  just copy relevant part of code and wrap it using  github syntax for code

- the edit() method is  only intended to work with dataedit so as explained in the doc  it build  query string parameters  according current PK and dataedit QS semantic.

- It's possible to reach what you need  ( edit record on this kind of uri /product/edit/{id} )  only with a dataform,  there are samples about that but just looking ant the demo http://www.rapyd.com/rapyd-demo/form  you can imagine how to change the `Article::find(1)` with  something like `Article::find($id)` passing the id via uri/parameter

In shorts.. when you need to control  also uri,  you need to use  dataform,  
when you need just a ready to use crud,  with full actions (including delete)  you can use a dataedit  but without the ability to customize  uri or qs  semantinc
