### ISSUE TITLE
 filter does not work

### ISSUE THREAD

**Issue by omrani6550** [zofe/rapyd-laravel#352]
hi ; my code  is in controller , but  filter does not work:

$filter = \DataFilter::source(DB::table('units')->select('code','name'));
        $filter->add('name','unit name', 'text');
        $filter->add('code','unit code', 'text');
        $filter->submit('search');
        $filter->reset('reset');
        $filter->build();
        $grid = \DataGrid::source(DB::table('units')->select('id','code','name')); //same source types of DataSet
        $grid->add('code','unit code', true); //field name, label, sortable
         $grid->add('name','unit name',true); //another way to filter
        $grid->edit('admin/cpanel/unit', 'edit','modify|delete|show');

        $grid->add('revision','ID')->cell( function( $value, $row) {
            return ($value != '') ? "rev.{$value}" : " {$row->id}";
        });
        $grid->row(function ($row) {
            if ($row->cell('code')->value < 100) {
                $row->cell('code')->style("color:Gray");
                $row->style("background-color:#CCFF66");
            }
        });
        $grid->link('admin/cpanel/unit/add',"new unit", "TR");  //add button
        $grid->orderBy('id','desc'); //default orderby
        $grid->paginate(5); //pa
        return view('cpanel.unit.index', compact('grid','filter'));

**Comment by zofe** [comment]
omrani6550..  you should use filter as source of grid   as explained in the doc
