### ISSUE TITLE
Any way to set Default filter for DataGrid?

### ISSUE THREAD

**Issue by CHOMNANP** [zofe/rapyd-laravel#353]
I would like my datagrid to load with Default filter.
I don't want user to to be able to see the client id. This is for security purpose.

       **$myClientID = SystemCustomHelper::getClientID();**
        
        $filter = \DataFilter::source(new Shop());
        //simple where with exact matchs
        $filter->add('name', 'Name', 'text');
        $filter->submit('search');
        $filter->reset('reset');
        $filter->build();
     
        $grid = \DataGrid::source($filter);        
        $grid->add('id', trans('shop.label_id'));         
        $grid->add('name', trans('shop.label_name')); 

        **$grid->setDefaultFilter('client_id', $myClientID);**

Thanks.

**Comment by zofe** [comment]
I hope to get the point.. (not well explained hehe)... 
A source can be a "query builder"  so you can make your "where" clause in the source.

I think this is a lack of knowledge of eloquent:
```php
$myClientID = SystemCustomHelper::getClientID();
$filter = \DataFilter::source(Shop()::where('client_id', $myClientID)); 
...
```

**Comment by CHOMNANP** [comment]
Understood.
Thank you :)
