### ISSUE TITLE
Is it possible to use 3level in data edit?

### ISSUE THREAD

**Issue by pastebimas** [zofe/rapyd-laravel#358]
Hi,
in datagrid I can use third level by:
$filter = \DataFilter::source(Event::with(['address' => function($q){
            $q->with('country');
        }]));

But in dataedit I mus use   new Event() and can't add any relations to it and in this way it is not nesting.
Is it possible, or not?
thanks

**Comment by zofe** [comment]
DataFilter (orDataGrid) is not strictly related with DataEdit.

if you need a related field inside the resulting grid (for Example a DataGrid) you can even use blade syntax with or without lazy load.

i.e.:

```php
        $filter = \DataFilter::source(Ambito::with('categoria','competenze'));
        $filter->add('titolo_ambito', 'Titolo Ambito', 'text');
        $filter->submit('Cerca');
        $filter->reset('reset');

        $grid = \DataGrid::source($filter); 
        $grid->add('{{ $categoria->it->NOME }}', 'categoria', true);
        $grid->add('{{ implode(", ", $competenze->lists("titolo_competenza")->all()) }}', 'competenze');
        
```

here as you can see  "$competenze" and "$categoria" are a relation "eager" loaded by with,  but if you need..  starting from there or from  "$row"  you can use eloquent lazy load in blade syntax.

In example  {{ @$row->myrel->myprop }} will lazy load myrel.. then display "myprop" value if exists

**Comment by zofe** [comment]
there are considerations..  when you use lazy load (so not "with" method),  the number of queries increase  (depending on numbers of rows for that page,  and deep level)  but usually is not a problem in a CRUD/Admin interface  which is the primary use for a tool like rapyd.

**Comment by pastebimas** [comment]
I made it working in dategrid ( my example just also used the filtering ). But the question is, can I make DataEdit with another level? Because if it has like
Post -> hasOne('address') and that address hasOne('country'), then using syntax like:
 $edit->add('nameOrSomething','text'); 
 $edit->add('address.street', 'Street','text');  // this one works normaly
 $edit->add('address.country.countryCode', 'Code of the country','text'); // that one works in datagrid, but not in dataedit.

Is is possible to get such one in editing or not? :)

**Comment by zofe** [comment]
Ok now I get the point.
No it's not implemented, it stops at 2 levels and not with all relations managed.
Whe also have others lack: polymorphic-relations for example.

The main suggestion is try to search in issues  (even closed one) there are solutions found by users.
Another suggestion is  .. don't use a DataEdit,  use a DataForm  and try to manage the post  and save the deepest level

Another one..  keep your crud simple, or don't use rapyd

**Comment by pastebimas** [comment]
actually, "keep your crud simple" is the best option. Just the matter of the perspective. Thanks !
