### ISSUE TITLE
Laravel 5.3 version

### ISSUE THREAD

**Issue by M0H3N** [zofe/rapyd-laravel#365]
hello 
Is this package stable for laravel 5.3?
if not ... please update it ... thanks

**Comment by zofe** [comment]
hi @M0H3N  this package is not tested in the 5.3
To be honest there aren't test, this is a big mistake for a mature package..
It's time to change.. 

Please check on a clean installation if the demo controller works.. If not I'll try to fix it.

**Comment by raulghm** [comment]
Hi, in a recently 5.3 installatcion I get:

```
FatalThrowableError in Rapyd.php line 40:
Call to a member function make() on null
```

:(

**Comment by CHOMNANP** [comment]
I'm using Rapyd with Laravel 5.3.
I didn't see any significant issue.

@raulghm,  anything I can help?

**Comment by raulghm** [comment]
Just installed again and works fine 👯 

For now is working in laravel 5.3

**Comment by zofe** [comment]
so it's ok to close right?
