### ISSUE TITLE
Data Grid and Eloquent collection 

### ISSUE THREAD

**Issue by arsenik** [zofe/rapyd-laravel#368]
I am trying to show a list of package name.
I have packages which is a many relationship with user.

Packages are show in json, I can see all package attributes. But I want to only show one attribute.
```
$this->grid->add('{{ implode("\n\n", $packages->all()) }}', 'Package')->filter('nl2br');
```

I tried 
```
$this->grid->add('{{ implode("\n\n", $packages->select("name")->all()) }}', 'Package')->filter('nl2br');
```
Does that look good to you?

**Comment by arsenik** [comment]
Found pluck!
``` 
$this->grid->add('{{ $packages->pluck("package_name", "package_value") }}', 'Package');
``` 
I am not sure what are the HTML options I can add to display 1 package per line?

**Comment by zofe** [comment]
when blade syntax is not enough to customize your cells/rows you can try with closure:

https://github.com/zofe/rapyd-laravel/wiki/DataGrid

**Comment by arsenik** [comment]
Closure it is, thank you.
``` 
//you can also access to the entire row dataset
$grid->add('revision', 'Article status')->cell( function ($value, $row) {
    if ($row->is_visible) {
        return '<u>'.link_to($row->full_url, "published", ['target'=>'_blank']).'</u>';
    }
    if ($row->pending_approval) {
        return 'pending approval';
    }
    ..
});
```
