### ISSUE TITLE
can i redirect to grid after insert?

### ISSUE THREAD

**Issue by danis963** [zofe/rapyd-laravel#382]
I need to reddirect automatically to grid after insert. Can you help me?

**Comment by zofe** [comment]
https://github.com/zofe/rapyd-laravel/wiki/DataEdit#back-action

**Comment by danis963** [comment]
can you give me an example?. I dont understand how use ->back automatically

**Comment by danis963** [comment]
**After save or update, redirects to panel/Controller/all automatically**

Controller:

$edit->saved(function() use ($edit)
{  
return Redirect('panel/Controller/all');
});

$edit->build();
return $edit->view('reedirect_view')->with('edit',$edit->returnEditView());

reedirect_view:
 {!! $edit !!}
