### ISSUE TITLE
Changing the order by to reverse the direction

### ISSUE THREAD

**Issue by bretto36** [zofe/rapyd-laravel#402]
So i have a DataGrid that has the age of the item in the grid. EG 400 days

The sort is based on the date

```
$grid->add('date', 'Age', 'date')->cell(function($value) {
            /** @var Carbon $value */
            return abs($value->diffInDays(Carbon::now())) . ' Days';
});
```
The order by arrows seems to work in reverse though. as i'm sorting on the date column. Is there any way to reverse the directions so the arrow means the opposite. When i click descending it gives the youngest first. and vice versa

**Comment by tacone** [comment]
There's no way. You may try to tackle the issue with some js or css trick though.
