### ISSUE TITLE
last inserted id form multistep edit

### ISSUE THREAD

**Issue by Francesco-1277** [zofe/rapyd-laravel#404]
Hi,

I read this https://github.com/zofe/rapyd-laravel/issues/142 
and this https://github.com/zofe/rapyd-laravel/issues/88

My purpose is to have a link to another page after I saved the record, so in my controller I've

`use \App\gestore_listini;
...

$edit->saved(function () use ($edit) {
    $edit->message("Record salvato");
    $edit->link("/gestore_listini/edit","Torna al modulo");
    $edit->link("/listino/$edit->gestore_listini->id","Associa questo listino ad una scala sconti");
});`

unfortunately I get this error:
ErrorException in gestore_listini_controller.php line xxx: Undefined property: Zofe\Rapyd\DataEdit\DataEdit::$gestore_listini

**Comment by hostingseguro** [comment]
Change this:

`$edit->link("/listino/$edit->gestore_listini->id","Associa questo listino ad una scala sconti");`

To:

`$edit->link("/listino/{{ $edit->model->id }}","Associa questo listino ad una scala sconti");`

Maybe you interpreted model as an example, but it is not you need to write explicitly model.

**Comment by Francesco-1277** [comment]
Infact I iterpreted `$edit->model` as an example, but if I try to use `link("/listino/{{ $edit->model->id }}"` I've this error:

FatalErrorException in gestore_listini_controller.php line 0: Method App\gestore_listini::__toString() must not throw an exception

Than, I tried to handle the error using this method in the model:

`public function __toString()  {
      try {
          return (string) $this->name;
      }
      catch (Exception $exception) {
          return '';
      }
  }`

but it prints a broken link  http://the_site/listino/->id

**Comment by hostingseguro** [comment]
I think that dataedit not supports blade syntax, but try this:

`$edit->link("/listino/" . $edit->model->id,"Associa questo listino ad una scala sconti");`

[https://github.com/zofe/rapyd-laravel/issues/101](url)

**Comment by Francesco-1277** [comment]
well, it works fine. Thanks for the help!
