### ISSUE TITLE
Add mutator for after-save URL

### ISSUE THREAD

**Issue by tacone** [zofe/rapyd-laravel#42]
After saving a data-edit, the user lands on the view mode of the data-edit itself. It'd be nice to be able to have him land straight back to the datagrid or any other URL of choice.

**Comment by sateesh15july** [comment]
I also have facing same issue. I want to redirect after successfull data edit to datagrid url.
But when I use below code then it only display form not my styling.
return $edit->view('shipMethod.edit_ship_method', compact('edit'));

and if use below code then view display proper but not redirection.
$this->layout->content = View::make('shipMethod.edit_ship_method', compact('edit'));

**Comment by larylinz** [comment]
within dataedit, why don't you use to redirect: $form->link(...)->back() ?
