### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::getOtherKey()

### ISSUE THREAD

**Issue by Vaulverin** [zofe/rapyd-laravel#420]
I've tryied to make checkboxgroup with relation BelongsToMany
`$form->add('permissions','Permissions','checkboxgroup')->options(Permission::all()->pluck('name', 'id'));`
and got this error.
Error is coming from Field class from `function setName($name)`:
```
if (is_a(@$this->relation, 'Illuminate\Database\Eloquent\Relations\BelongsToMany')){

                $this->rel_other_key = $this->relation->getOtherKey();

            }
```
So i had to inherit Checkboxgroup class and overwrite method setName and change method name to getQualifiedRelatedPivotKeyName(), so now it looks like this:
```
if (is_a(@$this->relation, 'Illuminate\Database\Eloquent\Relations\BelongsToMany')){

                $this->rel_other_key = $this->relation->getQualifiedRelatedPivotKeyName();

            }
```

Is there a better way? Or may be, i'm doing smth wrong?
I'm using Laravel Framework 5.5.13

**Comment by raylight75** [comment]
See this pull request[https://github.com/zofe/rapyd-laravel/pull/417](url)
