### ISSUE TITLE
How to pluck and implode into DataGrid

### ISSUE THREAD

**Issue by js5285** [zofe/rapyd-laravel#422]
Hi, 

May I know how to pluck an array list and show on DataGrid? 

`$row->cell('roles')->value = sprintf('<span class="label label-info">'. $user->roles()->pluck('name')->implode(', ') .'</span>');`

I have tried this method, but it show me raw text. 
`$grid->add('{{ implode(", ", $categories->lists("name")->all()) }}','Categories');`

Thanks in advance.

**Comment by tacone** [comment]
raw text means a php error was thrown. it's probably `$categories->lists("name")->toArray()`.

**Comment by js5285** [comment]
Hi Tacone, 

I still get the raw text.

**Comment by tacone** [comment]
could you post the full method source code?

**Comment by js5285** [comment]
`public function index()
{
	$users = User::with('roles')->get();

	$filter = DataFilter::source(new User);
	$filter->link('/users/create' , "Create New" , "TR");
	$filter->add('name' , Lang::get('global.name') , 'text');
	$filter->add('email' , Lang::get('global.email') , 'text');
	$filter->add('status' , Lang::get('global.status') , 'select')->options(User::LoadUserStatus());
	$filter->submit(Lang::get('global.search'));
	$filter->reset(Lang::get('global.reset'));
	$filter->build();
	
	$grid = DataGrid::source($filter)->orderby('id', 'asc');
	$grid->attributes(array("class" => "table table-striped"));
	$grid->add('<a href="users/{{ $id }}/edit" ><i class="glyphicon glyphicon-edit"></i></a>' , Lang::get('global.edit'))->style("width:1%");
	$grid->add('name' , Lang::get('global.name') , true);
	$grid->add('email' , Lang::get('global.email'));
	$grid->add('{{ implode(", ", $users->roles()->pluck("name")->all()) }}','Roles');
	$grid->add('status' , Lang::get('global.status'));
	$grid->paginate(10);
		
	return view('users.index' , compact('filter' , 'grid'));
}`

When I dump var it success. 

Thanks in advance.

**Comment by tacone** [comment]
It could be something like:

` {{ implode(", ", $roles->pluck("name")->toArray()) }} `

or 

` {{ implode(", ", $row->roles->pluck("name")->toArray()) }}`

**Comment by js5285** [comment]
Hi Tacone,

Thanks for your helps. 

Line below works. 
`{{ implode(", ", $row->roles->pluck("name")->toArray()) }}`
