### ISSUE TITLE
What is problem my code that does not show the result of the filtering؟

### ISSUE THREAD

**Issue by omidsaifpanahi** [zofe/rapyd-laravel#426]
// contrller
    public function index()
    {
        $filter = \DataFilter::source(City::with('Province'));
        $filter->add('name','نام شهر', 'text');
        $filter->add('Province.name','نام استان','tags');
        $filter->submit('search');
        $filter->reset('reset');
        $filter->build();

        $grid = \DataGrid::source(City::with('Province'));

        $grid->add('id','شماره', true)->style("width:100px");
        $grid->add('name','نام شهر', true)->filter('strip_tags|substr[0,20]');
          $grid->add('{{ $Province->name }}','استان', 'province_id');

        $grid->edit('city.edit', 'عملیات','modify|delete'); //shortcut to link DataEdit
        $grid->link(route('city.create'),"وارد کردن شهر جدید", "TR");
        $grid->orderBy('id','asc');
        $grid->paginate(10);
        $grid->attributes(array("class"=>"table table-striped"));
        return view('admin.city.index', compact('grid','filter'));
    }

// and file view/city/index
           
            {!! $filter !!}

            {!! $grid !!}

**Comment by tacone** [comment]
You have to pass the filter to the datagrid.

```php
$grid = \DataGrid::source($filter);
```
Good luck with your project! :)

**Comment by omidsaifpanahi** [comment]
# Thank you dear friend @tacone
