### ISSUE TITLE
Is it possible to get filtered data in controller?

### ISSUE THREAD

**Issue by seriousTom** [zofe/rapyd-laravel#439]
Hi,
I want to use rapyd data filter, but at first I need to proccess filtered data in my controller before passing it to view.
My code:
`public function index()
    {
        $user = auth()->user();

        $filter = \DataFilter::source(Task::with('project')->whereHas('project', function ($q) use ($user) {
            $q->where('user_group', $user->user_group_id);
        }));
        $filter->add('task_id', trans('ID'), 'text');
        $filter->add('name', trans('Name'), 'text');
        $filter->add('project_id', trans('Project ID'), 'select')->option('', trans('All projects'))->options(Project::orderBy('name', 'asc')->pluck('name', 'id'));
        $filter->submit('search');
        $filter->reset('reset');

        $tasks = $filter->query->get();
}`

But in controller this line $tasks = $filter->query->get(); doesnt return filtered data. It returns all data. I noticed that it works only when the filter view is rendered. So is it possible to achieve it in controller?

**Comment by seriousTom** [comment]
Nevermind. I was missing $filter->build()

**Comment by zofe** [comment]
k
