### ISSUE TITLE
File Field - Call to undefined method Illuminate\Events\Dispatcher::fire() on Laravel 5.8 

### ISSUE THREAD

**Issue by Presii** [zofe/rapyd-laravel#454]
Hello @zofe, currently I had an issue when try upload an image, the reason is the method fire from Events, the method isn't more longer support for laravel 5.8, from now you should use the contract method called "dispatch"

At File Field Class on the method upload you should change it
`Event::fire('rapyd.uploaded.'.$this->name);`

for this
`Event::dispatch('rapyd.uploaded.'.$this->name);`

**Comment by zeman** [comment]
Thanks @Presii, I had to apply this patch as well. Maybe submit a pull request?

**Comment by zofe** [comment]
seems ok also here
