### ISSUE TITLE
Laravel 6.0 Support

### ISSUE THREAD

**Issue by aftabkingdomvision** [zofe/rapyd-laravel#463]
Hello, Zofe I am using your packages for last two years. I found your data grid package is incredible for building application. I am setting up a new application for development. I see that your current packages is not compatible with Laravel 6.x. Can you please do something?

**Comment by luiscastror9** [comment]
you can changes some files and make compatible with 6.0, i did for laravel 5.7 and 5.8

**Comment by zhangyc310** [comment]
unsubscribe

Luis Castro <notifications@github.com> 于2020年3月1日周日 上午7:02写道：

**Comment by zofe** [comment]
some update is done, check readme
