### ISSUE TITLE
Undefined property: stdClass::$_edit Line 185

### ISSUE THREAD

**Issue by putWorkDev** [zofe/rapyd-laravel#54]
I don't know what i am doing wrong, but i forked your project, and now i can't seem to put edit colum on table rows (on datagrid) .

The error is always this: Undefined property: stdClass::$_edit Line 185

The code to build the table (in my UserController) is the following:

``` php
public function getIndex(){
            $grid = DataGrid::source(DB::table('users'));


            $grid->add('first_name','First Name');
            $grid->add('last_name','Last Name');

            $grid->edit('/admin/user/edit/1', 'Edit', 'modify');

            return \View::make('admin.pages.userView', compact('grid'));
}
```

The routes is the following:

``` php
Route::group(array('prefix' => 'admin', 'before' => 'auth.admin'), function(){

        Route::any('/', 'App\Controllers\Admin\PagesController@index');
        Route::resource('pages', 'App\Controllers\Admin\PagesController');
        Route::controller('user', 'App\Controllers\Admin\UserController'); 

});
```

**Comment by lms-it** [comment]
I was facing a similar problem with the same error here my code 
$clubs = DB::table('clubs')->skip(0)->take(10)->get();
I fixed this like this :
$clubs = (new Club)->skip(0)->take(10)->get();
I hope this can help someone ..

Thanks @zofe
